/**
 * CPV Stability Monitoring — privileged Cloud Functions.
 * All mutations are authorized here so client code is read-only for Firestore writes.
 */
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { type DocumentData, type Firestore, type WriteBatch } from 'firebase-admin/firestore';
import { getAdminFirestore } from './admin-app';
import { assertCpvBatchForProduct } from './cpv-batch-guard';

const STUDIES = 'stability_studies';
const SCHEDULES = 'stability_schedules';
const RESULTS = 'stability_results';
const MODULE = 'Stability Monitoring';
const STUDY_ROLES = ['super_admin', 'admin'];
const RESULT_ROLES = ['super_admin', 'admin', 'qc', 'qc_manager'];
const PULL_ROLES = ['super_admin', 'admin', 'warehouse', 'warehouse_manager'];
const REVIEW_ROLES = ['super_admin', 'admin', 'qa', 'head_qa', 'qa_manager'];
const VIEWER_ROLES = [...new Set([...STUDY_ROLES, ...RESULT_ROLES, ...PULL_ROLES, ...REVIEW_ROLES, 'production', 'production_manager', 'viewer', 'auditor'])];
const STUDY_TYPES = ['Long Term', 'Accelerated', 'Intermediate', 'Ongoing', 'Validation Batch', 'PV Batch', 'Commercial Batch', 'Photostability', 'In-use Stability'];
const CONDITIONS = ['25°C / 60% RH', '30°C / 65% RH', '30°C / 75% RH', '40°C / 75% RH', 'Other'];
const INTERVALS = ['Initial', '1 Month', '2 Month', '3 Month', '6 Month', '9 Month', '12 Month', '18 Month', '24 Month', '36 Month', '48 Month', '60 Month'];
const INTERVALS_BY_STUDY_TYPE: Record<string, string[]> = {
  'Long Term': ['Initial', '3 Month', '6 Month', '9 Month', '12 Month', '18 Month', '24 Month', '36 Month', '48 Month', '60 Month'],
  Accelerated: ['Initial', '1 Month', '3 Month', '6 Month'],
  Intermediate: ['Initial', '1 Month', '3 Month', '6 Month', '9 Month', '12 Month'],
  Ongoing: ['Initial', '3 Month', '6 Month', '12 Month'],
  'Validation Batch': ['Initial', '3 Month', '6 Month'],
  'PV Batch': ['Initial', '3 Month', '6 Month', '12 Month'],
  'Commercial Batch': ['Initial', '3 Month', '6 Month', '9 Month', '12 Month', '18 Month', '24 Month', '36 Month', '48 Month', '60 Month'],
  Photostability: ['Initial', '1 Month', '2 Month', '3 Month', '6 Month'],
  'In-use Stability': ['Initial', '1 Month', '2 Month', '3 Month', '6 Month'],
};

function required(value: unknown, field: string, max = 2000) {
  if (typeof value !== 'string' || !value.trim()) throw new HttpsError('invalid-argument', `${field} is required`);
  const result = value.trim();
  if (result.length > max) throw new HttpsError('invalid-argument', `${field} exceeds ${max} characters`);
  return result;
}
function optional(value: unknown, field: string, max = 2000) {
  if (value == null) return '';
  if (typeof value !== 'string') throw new HttpsError('invalid-argument', `${field} must be a string`);
  const result = value.trim();
  if (result.length > max) throw new HttpsError('invalid-argument', `${field} exceeds ${max} characters`);
  return result;
}
function reason(value: unknown) {
  const result = required(value, 'Change reason');
  if (result.length < 5) throw new HttpsError('invalid-argument', 'Change reason must be at least 5 characters');
  return result;
}
function number(value: unknown, field: string) {
  const result = Number(value);
  if (!Number.isFinite(result)) throw new HttpsError('invalid-argument', `${field} must be a finite number`);
  return result;
}
function optionalNumber(value: unknown) {
  if (value == null || value === '') return undefined;
  const result = Number(value);
  return Number.isFinite(result) ? result : undefined;
}
function validateEnum(value: string, options: readonly string[], field: string) {
  if (!options.includes(value)) throw new HttpsError('invalid-argument', `Invalid ${field}`);
  return value;
}
async function context(request: { auth?: { uid: string } | null }) {
  if (!request.auth?.uid) throw new HttpsError('unauthenticated', 'Authentication required');
  const firestore = getAdminFirestore();
  const profile = (await firestore.collection('profiles').doc(request.auth.uid).get()).data();
  return { firestore, profile, uid: request.auth.uid, name: String(profile?.full_name || profile?.email || request.auth.uid), role: String(profile?.role || '') };
}
function permit(profile: DocumentData | undefined, role: string, roles: string[], label: string) {
  if (!profile || profile.is_active !== true || !roles.includes(role)) throw new HttpsError('permission-denied', `${label} access required`);
}
function intervalToMonths(interval: string) { const match = interval.match(/^(\d+)\s*Month/i); return match ? Number(match[1]) : 0; }
function addMonthsToDate(date: string, months: number) { const result = new Date(date); result.setMonth(result.getMonth() + months); return result.toISOString().slice(0, 10); }
function evaluateStatus(observed: unknown, lower: number, upper: number, resultType: string, alertLow?: number, alertHigh?: number, actionLow?: number, actionHigh?: number) {
  if (resultType === 'Pass/Fail') return String(observed).toLowerCase() === 'pass' ? 'Complies' : 'OOS';
  if (resultType === 'Complies/Does Not Comply') { const value = String(observed).toLowerCase(); return value.includes('comply') && !value.includes('not') ? 'Complies' : 'OOS'; }
  const value = Number(observed);
  if (!Number.isFinite(value) || value < lower || value > upper) return 'OOS';
  if ((Number.isFinite(actionLow) && value < actionLow!) || (Number.isFinite(actionHigh) && value > actionHigh!)) return 'Action';
  if ((Number.isFinite(alertLow) && value < alertLow!) || (Number.isFinite(alertHigh) && value > alertHigh!)) return 'OOT';
  if (!Number.isFinite(alertLow) && !Number.isFinite(alertHigh)) { const range = upper - lower; if (range > 0 && (value < lower + range * .1 || value > upper - range * .1)) return 'OOT'; }
  return 'Complies';
}
function evaluateRisk(status: string, parameterName: string, ootCount: number) {
  if (status === 'OOS' || ootCount >= 2) return 'Critical';
  if (status === 'Action' || status === 'OOT') return 'High';
  if (parameterName.toLowerCase().includes('assay') && ootCount) return 'Medium';
  return 'Low';
}
function scheduleStatus(dueDate: string, actualPullingDate: string, resultEntryStatus: string, cancelled = false) {
  if (cancelled) return 'Cancelled';
  if (resultEntryStatus === 'Completed') return 'Testing Completed';
  if (actualPullingDate) return 'Pulled';
  const today = new Date().toISOString().slice(0, 10);
  if (dueDate < today) return 'Missed';
  const days = (new Date(dueDate).getTime() - new Date(today).getTime()) / 86400000;
  return days <= 7 ? 'Due Soon' : 'Pending';
}
function studyNumber(batchNumber: string, studyType: string) { return `STAB-CPV-${new Date().getFullYear()}-${batchNumber}-${studyType}`.replace(/\s+/g, '-').toUpperCase().slice(0, 60); }
function resultNumber(batchNumber: string, interval: string, parameter: string) { return `STB-${batchNumber}-${interval}-${parameter}`.replace(/\s+/g, '-').toUpperCase(); }
async function assertOperationalProduct(firestore: Firestore, id: string) {
  const product = await firestore.collection('cpv_products').doc(id).get();
  if (!product.exists || product.data()?.isDeleted === true) throw new HttpsError('failed-precondition', 'CPV product not found');
  if (!['Active', 'Under Review', 'Approved'].includes(String(product.data()?.cpvStatus || ''))) throw new HttpsError('failed-precondition', 'Selected CPV product is not operational');
}
function audit(batch: WriteBatch, firestore: Firestore, input: { uid: string; name: string; id: string; docNo?: string; action: string; description: string; now: string; oldValue?: unknown; newValue?: unknown; reason?: string; esign?: boolean }) {
  const base = { recordId: input.id, documentId: input.id, documentNumber: input.docNo || '', actionType: input.action, action: input.action, actionDescription: input.description, oldValue: input.oldValue ?? null, newValue: input.newValue ?? null, reason: input.reason || '', userId: input.uid, userName: input.name, performedBy: input.name, timestamp: input.now, createdAt: input.now };
  batch.set(firestore.collection('audit_trail').doc(), { ...base, auditId: `AUD-STB-${Date.now().toString(36).toUpperCase()}`, dateTime: input.now, moduleName: 'CPV', subModule: MODULE, collectionName: RESULTS, electronicSignature: input.esign === true, source: 'cpv-stability-admin', immutable: true, appendOnly: true });
  batch.set(firestore.collection('audit_logs').doc(), { module: MODULE, action: input.action, recordId: input.id, description: input.description, performedBy: input.name, userId: input.uid, reason: input.reason || '', timestamp: input.now, createdAt: input.now, status: 'Success', electronicSignature: input.esign === true, source: 'cpv-stability-admin' });
  batch.set(firestore.collection('cpv_audit_trail').doc(), { moduleName: MODULE, ...base, status: 'Success', electronicSignature: input.esign === true, source: 'cpv-stability-admin' });
}
function notify(batch: WriteBatch, firestore: Firestore, uid: string, id: string, title: string, message: string, now: string) {
  batch.set(firestore.collection('notifications').doc(), { userId: uid, title, message, type: 'cpv_stability', recordId: id, module: MODULE, href: `/cpv/stability-monitoring/${id}`, read: false, createdAt: now });
}
function studyPayload(data: Record<string, unknown>, existing?: DocumentData) {
  const studyType = validateEnum(required(data.studyType ?? existing?.studyType, 'Study type', 80), STUDY_TYPES, 'study type');
  const storageCondition = validateEnum(required(data.storageCondition ?? existing?.storageCondition, 'Storage condition', 80), CONDITIONS, 'storage condition');
  return { cpvProductId: required(data.cpvProductId ?? existing?.cpvProductId, 'CPV product', 120), productName: required(data.productName ?? existing?.productName, 'Product name', 200), productCode: required(data.productCode ?? existing?.productCode, 'Product code', 80), productVersion: optional(data.productVersion ?? existing?.productVersion, 'Product version', 40), strength: optional(data.strength ?? existing?.strength, 'Strength', 80), dosageForm: optional(data.dosageForm ?? existing?.dosageForm, 'Dosage form', 80), packSize: optional(data.packSize ?? existing?.packSize, 'Pack size', 80), packagingType: optional(data.packagingType ?? existing?.packagingType, 'Packaging type', 80), shelfLifeMonths: optionalNumber(data.shelfLifeMonths ?? existing?.shelfLifeMonths) ?? null, batchNumber: required(data.batchNumber ?? existing?.batchNumber, 'Batch number', 80), manufacturingDate: required(data.manufacturingDate ?? existing?.manufacturingDate, 'Manufacturing date', 40), expiryDate: required(data.expiryDate ?? existing?.expiryDate, 'Expiry date', 40), studyType, storageCondition, studyStartDate: required(data.studyStartDate ?? existing?.studyStartDate, 'Study start date', 40), studyEndDate: optional(data.studyEndDate ?? existing?.studyEndDate, 'Study end date', 40), protocolVersion: optional(data.protocolVersion ?? existing?.protocolVersion, 'Protocol version', 40), specificationVersion: optional(data.specificationVersion ?? existing?.specificationVersion, 'Specification version', 40), site: optional(data.site ?? existing?.site, 'Site', 120), department: optional(data.department ?? existing?.department, 'Department', 120), chamberId: optional(data.chamberId ?? existing?.chamberId, 'Chamber id', 120), chamberName: optional(data.chamberName ?? existing?.chamberName, 'Chamber name', 200), remarks: optional(data.remarks ?? existing?.remarks, 'Remarks') };
}
function resultPayload(data: Record<string, unknown>, existing?: DocumentData) {
  const resultType = optional(data.resultType ?? existing?.resultType, 'Result type', 40) || 'Numeric';
  const lowerLimit = number(data.lowerLimit ?? existing?.lowerLimit, 'Lower limit'), upperLimit = number(data.upperLimit ?? existing?.upperLimit, 'Upper limit');
  if (lowerLimit >= upperLimit) throw new HttpsError('invalid-argument', 'Upper limit must be greater than lower limit');
  const observed = data.observedResult ?? existing?.observedResult;
  if (observed == null || observed === '') throw new HttpsError('invalid-argument', 'Observed result is required');
  return { studyId: required(data.studyId ?? existing?.studyId, 'Study id', 120), stabilityStudyNumber: required(data.stabilityStudyNumber ?? existing?.stabilityStudyNumber, 'Study number', 120), cpvProductId: required(data.cpvProductId ?? existing?.cpvProductId, 'CPV product', 120), productName: required(data.productName ?? existing?.productName, 'Product name', 200), productCode: required(data.productCode ?? existing?.productCode, 'Product code', 80), batchNumber: required(data.batchNumber ?? existing?.batchNumber, 'Batch number', 80), manufacturingDate: required(data.manufacturingDate ?? existing?.manufacturingDate, 'Manufacturing date', 40), expiryDate: required(data.expiryDate ?? existing?.expiryDate, 'Expiry date', 40), studyType: validateEnum(required(data.studyType ?? existing?.studyType, 'Study type', 80), STUDY_TYPES, 'study type'), storageCondition: validateEnum(required(data.storageCondition ?? existing?.storageCondition, 'Storage condition', 80), CONDITIONS, 'storage condition'), pullingInterval: validateEnum(required(data.pullingInterval ?? existing?.pullingInterval, 'Pulling interval', 40), INTERVALS, 'pulling interval'), samplePullingDueDate: optional(data.samplePullingDueDate ?? existing?.samplePullingDueDate, 'Sample pulling due date', 40), actualSamplePullingDate: optional(data.actualSamplePullingDate ?? existing?.actualSamplePullingDate, 'Actual sample pulling date', 40), testDate: required(data.testDate ?? existing?.testDate, 'Test date', 40), parameterCode: required(data.parameterCode ?? existing?.parameterCode, 'Parameter code', 80), parameterName: required(data.parameterName ?? existing?.parameterName, 'Parameter name', 200), observedResult: resultType === 'Numeric' && Number.isFinite(Number(observed)) ? Number(observed) : String(observed).trim(), targetValue: optionalNumber(data.targetValue ?? existing?.targetValue) ?? null, lowerLimit, upperLimit, alertLimitLow: optionalNumber(data.alertLimitLow ?? existing?.alertLimitLow) ?? null, alertLimitHigh: optionalNumber(data.alertLimitHigh ?? existing?.alertLimitHigh) ?? null, actionLimitLow: optionalNumber(data.actionLimitLow ?? existing?.actionLimitLow) ?? null, actionLimitHigh: optionalNumber(data.actionLimitHigh ?? existing?.actionLimitHigh) ?? null, unit: optional(data.unit ?? existing?.unit, 'Unit', 40), resultType, analyst: required(data.analyst ?? existing?.analyst, 'Analyst', 120), reviewedBy: optional(data.reviewedBy ?? existing?.reviewedBy, 'Reviewed by', 120), reviewDate: optional(data.reviewDate ?? existing?.reviewDate, 'Review date', 40), chamberId: optional(data.chamberId ?? existing?.chamberId, 'Chamber id', 120), chamberName: optional(data.chamberName ?? existing?.chamberName, 'Chamber name', 200), remarks: optional(data.remarks ?? existing?.remarks, 'Remarks') };
}
async function duplicateStudy(firestore: Firestore, payload: ReturnType<typeof studyPayload>, exclude?: string) { const snap = await firestore.collection(STUDIES).where('batchNumber', '==', payload.batchNumber).where('studyType', '==', payload.studyType).limit(30).get(); return snap.docs.some((d) => d.id !== exclude && d.data()?.isDeleted !== true && d.data()?.storageCondition === payload.storageCondition); }
async function duplicateResult(firestore: Firestore, payload: ReturnType<typeof resultPayload>, exclude?: string) { const snap = await firestore.collection(RESULTS).where('batchNumber', '==', payload.batchNumber).where('pullingInterval', '==', payload.pullingInterval).where('parameterCode', '==', payload.parameterCode).limit(30).get(); return snap.docs.some((d) => d.id !== exclude && d.data()?.isDeleted !== true && d.data()?.studyType === payload.studyType && d.data()?.storageCondition === payload.storageCondition); }
async function ootCount(firestore: Firestore, batchNumber: string, parameterName: string) { const snap = await firestore.collection(RESULTS).where('batchNumber', '==', batchNumber).where('parameterName', '==', parameterName).limit(100).get(); return new Set(snap.docs.filter((d) => d.data()?.isDeleted !== true && ['OOT', 'Action'].includes(String(d.data()?.status))).map((d) => String(d.data()?.pullingInterval))).size; }

export const createAdminStabilityStudy = onCall(async (request) => {
  const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, STUDY_ROLES, 'Stability study');
  const data = (request.data || {}) as Record<string, unknown>, changeReason = reason(data.changeReason), payload = studyPayload(data);
  await assertOperationalProduct(firestore, payload.cpvProductId); await assertCpvBatchForProduct(firestore, payload.cpvProductId, payload.batchNumber); if (await duplicateStudy(firestore, payload)) throw new HttpsError('already-exists', 'Stability study already exists for this batch, type and condition');
  const now = new Date().toISOString(), ref = firestore.collection(STUDIES).doc(), record = { ...payload, id: ref.id, stabilityStudyNumber: studyNumber(payload.batchNumber, payload.studyType), stabilityMonitoringId: studyNumber(payload.batchNumber, payload.studyType), studyStatus: 'Ongoing', isDeleted: false, createdAt: now, updatedAt: now, createdBy: uid, updatedBy: uid, createdByName: name, updatedByName: name, changeReason };
  const batch = firestore.batch(); batch.set(ref, record); audit(batch, firestore, { uid, name, id: ref.id, docNo: record.stabilityStudyNumber, action: 'Stability Study Created', description: `Created ${record.stabilityStudyNumber}`, newValue: record, reason: changeReason, now }); await batch.commit(); return record;
});
export const updateAdminStabilityStudy = onCall(async (request) => {
  const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, STUDY_ROLES, 'Stability study'); const data = (request.data || {}) as Record<string, unknown>, id = required(data.id, 'Study id', 120), changeReason = reason(data.changeReason), snap = await firestore.collection(STUDIES).doc(id).get();
  if (!snap.exists || snap.data()?.isDeleted) throw new HttpsError('not-found', 'Stability study not found'); const payload = studyPayload(data, snap.data()); if (await duplicateStudy(firestore, payload, id)) throw new HttpsError('already-exists', 'Duplicate stability study');
  const now = new Date().toISOString(), updates = { ...payload, stabilityStudyNumber: studyNumber(payload.batchNumber, payload.studyType), stabilityMonitoringId: studyNumber(payload.batchNumber, payload.studyType), updatedAt: now, updatedBy: uid, updatedByName: name, changeReason }, batch = firestore.batch(); batch.update(snap.ref, updates); audit(batch, firestore, { uid, name, id, docNo: updates.stabilityStudyNumber, action: 'Stability Study Updated', description: `Updated ${updates.stabilityStudyNumber}`, oldValue: snap.data(), newValue: updates, reason: changeReason, now }); await batch.commit(); return { id, ...snap.data(), ...updates };
});
export const generateAdminStabilitySchedule = onCall(async (request) => {
  const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, [...STUDY_ROLES, ...RESULT_ROLES], 'Stability schedule'); const data = (request.data || {}) as Record<string, unknown>, studyId = required(data.studyId, 'Study id', 120), changeReason = reason(data.changeReason || 'Generate stability schedule'), study = await firestore.collection(STUDIES).doc(studyId).get();
  if (!study.exists || study.data()?.isDeleted) throw new HttpsError('not-found', 'Stability study not found'); const existing = await firestore.collection(SCHEDULES).where('studyId', '==', studyId).limit(1).get(); if (!existing.empty) return { schedules: existing.docs.map((d) => ({ id: d.id, ...d.data() })) };
  const source = study.data() || {}, intervals = Array.isArray(data.intervals) && data.intervals.length ? data.intervals.map(String) : INTERVALS_BY_STUDY_TYPE[String(source.studyType)] || INTERVALS_BY_STUDY_TYPE['Long Term']; intervals.forEach((value) => validateEnum(value, INTERVALS, 'pulling interval'));
  const now = new Date().toISOString(), batch = firestore.batch(), schedules: Record<string, unknown>[] = []; for (const interval of intervals) { const ref = firestore.collection(SCHEDULES).doc(), dueDate = addMonthsToDate(String(source.studyStartDate), intervalToMonths(interval)), row = { id: ref.id, studyId, stabilityStudyNumber: source.stabilityStudyNumber, batchNumber: source.batchNumber, studyType: source.studyType, storageCondition: source.storageCondition, interval, samplePullingDueDate: dueDate, actualPullingDate: '', resultEntryStatus: 'Pending', scheduleStatus: scheduleStatus(dueDate, '', 'Pending'), isDeleted: false, createdAt: now, updatedAt: now, createdBy: uid, updatedBy: uid }; schedules.push(row); batch.set(ref, row); } audit(batch, firestore, { uid, name, id: studyId, docNo: String(source.stabilityStudyNumber || ''), action: 'Stability Schedule Generated', description: `Generated ${schedules.length} schedule rows`, newValue: { intervals }, reason: changeReason, now }); await batch.commit(); return { schedules };
});
export const updateAdminStabilityPull = onCall(async (request) => {
  const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, PULL_ROLES, 'Sample pull'); const data = (request.data || {}) as Record<string, unknown>, id = required(data.scheduleId ?? data.id, 'Schedule id', 120), changeReason = reason(data.changeReason || 'Update sample pull'), snap = await firestore.collection(SCHEDULES).doc(id).get(); if (!snap.exists || snap.data()?.isDeleted) throw new HttpsError('not-found', 'Schedule not found');
  const existing = snap.data() || {}, actualPullingDate = optional(data.actualPullingDate, 'Actual pulling date', 40), now = new Date().toISOString(), updates = { actualPullingDate, scheduleStatus: scheduleStatus(String(existing.samplePullingDueDate || ''), actualPullingDate, String(existing.resultEntryStatus || 'Pending')), updatedAt: now, updatedBy: uid, updatedByName: name, changeReason }, batch = firestore.batch(); batch.update(snap.ref, updates); audit(batch, firestore, { uid, name, id, docNo: String(existing.stabilityStudyNumber || ''), action: 'Stability Sample Pull Updated', description: `Sample pull ${updates.scheduleStatus}`, oldValue: existing, newValue: updates, reason: changeReason, now }); if (updates.scheduleStatus === 'Missed') notify(batch, firestore, uid, id, 'Stability sample missed', `${existing.batchNumber}: ${existing.interval} sample pull missed`, now); await batch.commit(); return { id, ...existing, ...updates };
});
export const refreshAdminStabilitySchedules = onCall(async (request) => {
  const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, [...PULL_ROLES, ...STUDY_ROLES, ...RESULT_ROLES], 'Stability schedule'); const snap = await firestore.collection(SCHEDULES).limit(500).get(), now = new Date().toISOString(), batch = firestore.batch(); let updated = 0;
  snap.docs.forEach((doc) => { const value = doc.data(); if (value.isDeleted === true) return; const status = scheduleStatus(String(value.samplePullingDueDate || ''), String(value.actualPullingDate || ''), String(value.resultEntryStatus || 'Pending'), value.scheduleStatus === 'Cancelled'); if (status !== value.scheduleStatus) { batch.update(doc.ref, { scheduleStatus: status, updatedAt: now, updatedBy: uid, updatedByName: name }); updated += 1; } }); audit(batch, firestore, { uid, name, id: 'refresh', action: 'Stability Schedules Refreshed', description: `Refreshed ${updated} schedule statuses`, newValue: { updated }, reason: 'Refresh schedule statuses', now }); await batch.commit(); return { updated };
});
async function createResult(firestore: Firestore, data: Record<string, unknown>, uid: string, name: string, changeReason: string) {
  const payload = resultPayload(data); await assertOperationalProduct(firestore, payload.cpvProductId); await assertCpvBatchForProduct(firestore, payload.cpvProductId, payload.batchNumber); if (await duplicateResult(firestore, payload)) throw new HttpsError('already-exists', 'Result already exists for this batch, interval and parameter');
  const status = evaluateStatus(payload.observedResult, payload.lowerLimit, payload.upperLimit, payload.resultType, payload.alertLimitLow ?? undefined, payload.alertLimitHigh ?? undefined, payload.actionLimitLow ?? undefined, payload.actionLimitHigh ?? undefined), previousOot = await ootCount(firestore, payload.batchNumber, payload.parameterName), riskLevel = evaluateRisk(status, payload.parameterName, previousOot), now = new Date().toISOString(), ref = firestore.collection(RESULTS).doc(), record = { ...payload, id: ref.id, stabilityMonitoringId: resultNumber(payload.batchNumber, payload.pullingInterval, payload.parameterCode), scheduleId: '', status, riskLevel, ootRequired: status === 'OOT', oosRequired: status === 'OOS', deviationRequired: ['OOT', 'OOS', 'Action'].includes(status), capaRequired: previousOot >= 2 || status === 'OOS', linkedOosNumber: '', linkedDeviationNumber: '', linkedCapaNumber: '', reviewStatus: 'Draft', isLocked: false, attachments: [], isDeleted: false, createdAt: now, updatedAt: now, createdBy: uid, updatedBy: uid, createdByName: name, updatedByName: name, changeReason };
  const batch = firestore.batch(); batch.set(ref, record); const schedules = await firestore.collection(SCHEDULES).where('studyId', '==', payload.studyId).where('interval', '==', payload.pullingInterval).limit(1).get(); if (!schedules.empty) { batch.update(schedules.docs[0].ref, { resultEntryStatus: 'Completed', scheduleStatus: 'Testing Completed', updatedAt: now, updatedBy: uid }); record.scheduleId = schedules.docs[0].id; } audit(batch, firestore, { uid, name, id: ref.id, docNo: record.stabilityMonitoringId, action: 'Stability Result Created', description: `Recorded ${payload.parameterName} → ${status}`, newValue: { status, riskLevel }, reason: changeReason, now }); if (['OOS', 'OOT'].includes(status)) notify(batch, firestore, uid, ref.id, `Stability ${status}`, `${payload.batchNumber}: ${payload.parameterName} ${status}`, now); await batch.commit(); return record;
}
export const createAdminStabilityResult = onCall(async (request) => { const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, RESULT_ROLES, 'Stability result'); const data = (request.data || {}) as Record<string, unknown>; return createResult(firestore, data, uid, name, reason(data.changeReason)); });
export const updateAdminStabilityResult = onCall(async (request) => {
  const { firestore, profile, uid, name, role } = await context(request); const data = (request.data || {}) as Record<string, unknown>, id = required(data.id, 'Result id', 120), changeReason = reason(data.changeReason), snap = await firestore.collection(RESULTS).doc(id).get(); if (!snap.exists || snap.data()?.isDeleted) throw new HttpsError('not-found', 'Stability result not found'); const existing = snap.data() || {}, qaOverride = data.qaOverride === true;
  if (existing.isLocked && existing.reviewStatus === 'Approved') { if (!qaOverride) throw new HttpsError('failed-precondition', 'Approved stability result is locked. QA override required'); permit(profile, role, REVIEW_ROLES, 'QA override'); if (data.esignConfirmed !== true) throw new HttpsError('failed-precondition', 'Electronic signature required for QA override'); } else permit(profile, role, RESULT_ROLES, 'Stability result');
  const payload = resultPayload(data, existing); if (await duplicateResult(firestore, payload, id)) throw new HttpsError('already-exists', 'Duplicate stability result'); const status = evaluateStatus(payload.observedResult, payload.lowerLimit, payload.upperLimit, payload.resultType, payload.alertLimitLow ?? undefined, payload.alertLimitHigh ?? undefined, payload.actionLimitLow ?? undefined, payload.actionLimitHigh ?? undefined), prior = await ootCount(firestore, payload.batchNumber, payload.parameterName), now = new Date().toISOString(), updates = { ...payload, stabilityMonitoringId: resultNumber(payload.batchNumber, payload.pullingInterval, payload.parameterCode), status, riskLevel: evaluateRisk(status, payload.parameterName, prior), ootRequired: status === 'OOT', oosRequired: status === 'OOS', deviationRequired: ['OOT', 'OOS', 'Action'].includes(status), capaRequired: prior >= 2 || status === 'OOS', updatedAt: now, updatedBy: uid, updatedByName: name, changeReason }, batch = firestore.batch(); batch.update(snap.ref, updates); audit(batch, firestore, { uid, name, id, docNo: updates.stabilityMonitoringId, action: qaOverride ? 'Stability QA Override' : 'Stability Result Updated', description: `Updated ${payload.parameterName} → ${status}`, oldValue: existing, newValue: updates, reason: changeReason, now, esign: qaOverride }); if (['OOS', 'OOT'].includes(status)) notify(batch, firestore, uid, id, `Stability ${status}`, `${payload.batchNumber}: ${payload.parameterName} ${status}`, now); await batch.commit(); return { id, ...existing, ...updates };
});
export const reviewAdminStabilityResult = onCall(async (request) => { const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, REVIEW_ROLES, 'Stability review'); const data = (request.data || {}) as Record<string, unknown>, id = required(data.id, 'Result id', 120), changeReason = reason(data.changeReason || 'Submitted for QA review'), snap = await firestore.collection(RESULTS).doc(id).get(); if (!snap.exists || snap.data()?.isDeleted) throw new HttpsError('not-found', 'Stability result not found'); if (snap.data()?.reviewStatus === 'Approved') throw new HttpsError('failed-precondition', 'Approved results cannot be reopened'); const now = new Date().toISOString(), updates = { reviewStatus: 'Under Review', reviewedBy: name, reviewDate: now.slice(0, 10), updatedAt: now, updatedBy: uid, updatedByName: name, changeReason }, batch = firestore.batch(); batch.update(snap.ref, updates); audit(batch, firestore, { uid, name, id, docNo: String(snap.data()?.stabilityMonitoringId || ''), action: 'Stability Review Submitted', description: 'Submitted for QA review', oldValue: snap.data()?.reviewStatus, newValue: 'Under Review', reason: changeReason, now }); await batch.commit(); return { id, ...snap.data(), ...updates }; });
export const approveAdminStabilityResult = onCall(async (request) => { const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, REVIEW_ROLES, 'Stability approval'); const data = (request.data || {}) as Record<string, unknown>, id = required(data.id, 'Result id', 120), changeReason = reason(data.changeReason); if (data.esignConfirmed !== true) throw new HttpsError('failed-precondition', 'Electronic signature confirmation required to approve'); const snap = await firestore.collection(RESULTS).doc(id).get(); if (!snap.exists || snap.data()?.isDeleted) throw new HttpsError('not-found', 'Stability result not found'); if (!['Draft', 'Under Review'].includes(String(snap.data()?.reviewStatus))) throw new HttpsError('failed-precondition', 'Result cannot be approved from current status'); const now = new Date().toISOString(), updates = { reviewStatus: 'Approved', isLocked: true, reviewedBy: name, reviewDate: now.slice(0, 10), updatedAt: now, updatedBy: uid, updatedByName: name, changeReason }, batch = firestore.batch(); batch.update(snap.ref, updates); audit(batch, firestore, { uid, name, id, docNo: String(snap.data()?.stabilityMonitoringId || ''), action: 'Stability Result Approved', description: 'Approved and locked stability result', reason: changeReason, now, esign: true }); await batch.commit(); return { id, ...snap.data(), ...updates }; });
export const bulkCreateAdminStabilityResults = onCall({ timeoutSeconds: 120 }, async (request) => { const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, RESULT_ROLES, 'Stability result'); const data = (request.data || {}) as Record<string, unknown>, rows = Array.isArray(data.rows) ? data.rows as Record<string, unknown>[] : [], changeReason = reason(data.changeReason || 'Bulk stability result entry'); if (!rows.length || rows.length > 100) throw new HttpsError('invalid-argument', 'Bulk entry must contain 1 to 100 results'); const errors: string[] = []; let created = 0; for (const row of rows) { try { await createResult(firestore, { ...row, changeReason }, uid, name, changeReason); created += 1; } catch (error) { errors.push(error instanceof Error ? error.message : 'Unknown bulk error'); } } return { created, errors }; });
export const softDeleteAdminStabilityResult = onCall(async (request) => { const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, REVIEW_ROLES, 'Stability archive'); const data = (request.data || {}) as Record<string, unknown>, id = required(data.id, 'Result id', 120), changeReason = reason(data.changeReason); if (data.esignConfirmed !== true) throw new HttpsError('failed-precondition', 'Electronic signature required to archive'); const snap = await firestore.collection(RESULTS).doc(id).get(); if (!snap.exists || snap.data()?.isDeleted) throw new HttpsError('not-found', 'Stability result not found'); if (snap.data()?.reviewStatus === 'Approved') throw new HttpsError('failed-precondition', 'Cannot delete approved stability results'); const now = new Date().toISOString(), updates = { isDeleted: true, deletedAt: now, deletedBy: uid, updatedAt: now, updatedBy: uid, updatedByName: name, changeReason }, batch = firestore.batch(); batch.update(snap.ref, updates); audit(batch, firestore, { uid, name, id, docNo: String(snap.data()?.stabilityMonitoringId || ''), action: 'Stability Result Archived', description: 'Soft-deleted stability result', reason: changeReason, now, esign: true }); await batch.commit(); return { success: true, id }; });
export const updateAdminStabilityAttachments = onCall(async (request) => { const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, RESULT_ROLES, 'Stability attachment'); const data = (request.data || {}) as Record<string, unknown>, id = required(data.id, 'Result id', 120), changeReason = reason(data.changeReason), attachments = Array.isArray(data.attachments) ? data.attachments : []; const snap = await firestore.collection(RESULTS).doc(id).get(); if (!snap.exists || snap.data()?.isDeleted) throw new HttpsError('not-found', 'Stability result not found'); const now = new Date().toISOString(), updates = { attachments, updatedAt: now, updatedBy: uid, updatedByName: name, changeReason }, batch = firestore.batch(); batch.update(snap.ref, updates); audit(batch, firestore, { uid, name, id, docNo: String(snap.data()?.stabilityMonitoringId || ''), action: 'Stability Attachments Updated', description: `Updated ${attachments.length} attachment(s)`, oldValue: snap.data()?.attachments || [], newValue: attachments, reason: changeReason, now }); await batch.commit(); return { id, ...snap.data(), ...updates }; });
export const logAdminStabilityExport = onCall(async (request) => { const { firestore, profile, uid, name, role } = await context(request); permit(profile, role, VIEWER_ROLES, 'Stability export'); const data = (request.data || {}) as Record<string, unknown>, now = new Date().toISOString(), batch = firestore.batch(); audit(batch, firestore, { uid, name, id: 'export', action: 'Stability Export', description: `Exported ${Number(data.count || 0)} records`, newValue: { count: Number(data.count || 0), format: optional(data.format, 'Format', 40) || 'CSV' }, reason: optional(data.changeReason, 'Change reason', 500) || 'Export', now }); await batch.commit(); return { success: true }; });
