import type { AppModule } from '@/lib/permissions';

/** Maps route prefixes to application modules for access control */
export const ROUTE_MODULE_MAP: Array<{ prefix: string; module: AppModule }> = [
  { prefix: '/admin', module: 'admin' },
  { prefix: '/dashboard/admin', module: 'admin' },
  { prefix: '/cpv', module: 'cpv' },
  { prefix: '/pqr', module: 'pqr' },
  { prefix: '/dashboard/pqr', module: 'pqr' },
  { prefix: '/qms/deviation', module: 'deviation' },
  { prefix: '/qms/oos', module: 'oos' },
  { prefix: '/qms/capa', module: 'capa' },
  { prefix: '/qms/change-control', module: 'change_control' },
  { prefix: '/qms/stability', module: 'stability' },
  { prefix: '/qms/complaints', module: 'complaints' },
  { prefix: '/qms/recall', module: 'recall' },
  { prefix: '/qms/documents', module: 'dms' },
  { prefix: '/qms/wi-management', module: 'dms' },
  { prefix: '/qms/wi', module: 'dms' },
  { prefix: '/qms/work-instructions', module: 'dms' },
  { prefix: '/qms/forms', module: 'dms' },
  { prefix: '/qms/templates', module: 'dms' },
  { prefix: '/qms/forms-management', module: 'dms' },
  { prefix: '/qms/template-library', module: 'dms' },
  { prefix: '/qms/document-distribution', module: 'dms' },
  { prefix: '/qms/controlled-distribution', module: 'dms' },
  { prefix: '/qms/document-acknowledgement', module: 'dms' },
  { prefix: '/qms/read-confirmation', module: 'dms' },
  { prefix: '/qms/document-read-confirmation', module: 'dms' },
  { prefix: '/qms/version-control', module: 'dms' },
  { prefix: '/qms/document-versions', module: 'dms' },
  { prefix: '/qms/document-review', module: 'dms' },
  { prefix: '/qms/review-workflow', module: 'dms' },
  { prefix: '/qms/document-approval', module: 'dms' },
  { prefix: '/qms/approval-workflow', module: 'dms' },
  { prefix: '/qms/effective-dates', module: 'dms' },
  { prefix: '/qms/document-effective-dates', module: 'dms' },
  { prefix: '/qms/periodic-review', module: 'dms' },
  { prefix: '/qms/document-review-schedule', module: 'dms' },
  { prefix: '/qms/change-impact', module: 'dms' },
  { prefix: '/qms/document-impact', module: 'dms' },
  { prefix: '/qms/impact-assessment', module: 'dms' },
  { prefix: '/qms/archive', module: 'dms' },
  { prefix: '/qms/document-archive', module: 'dms' },
  { prefix: '/qms/archive-management', module: 'dms' },
  { prefix: '/qms/retention', module: 'dms' },
  { prefix: '/qms/disposal', module: 'dms' },
  { prefix: '/qms/records-retention', module: 'dms' },
  { prefix: '/qms/document-retention', module: 'dms' },
  { prefix: '/qms/external-documents', module: 'dms' },
  { prefix: '/qms/external-document-management', module: 'dms' },
  { prefix: '/qms/document-control', module: 'dms' },
  { prefix: '/qms/print-control', module: 'dms' },
  { prefix: '/qms/controlled-printing', module: 'dms' },
  { prefix: '/qms/document-printing', module: 'dms' },
  { prefix: '/qms/watermarks', module: 'dms' },
  { prefix: '/qms/document-watermarks', module: 'dms' },
  { prefix: '/qms/watermark-management', module: 'dms' },
  { prefix: '/qms/documents/audit-trail', module: 'dms' },
  { prefix: '/qms/document-audit', module: 'dms' },
  { prefix: '/qms/document-history', module: 'dms' },
  { prefix: '/qms/dms/audit', module: 'dms' },
  { prefix: '/qms/audit-trail', module: 'dms' },
  { prefix: '/qms/system/electronic-signatures', module: 'dms' },
  { prefix: '/qms/esignatures', module: 'dms' },
  { prefix: '/qms/e-signatures', module: 'dms' },
  { prefix: '/qms/part11-signatures', module: 'dms' },
  { prefix: '/qms/sop-management', module: 'dms' },
  { prefix: '/qms/sop', module: 'dms' },
  { prefix: '/qms/document-management', module: 'dms' },
  { prefix: '/qms/document-master', module: 'dms' },
  { prefix: '/qms/dms', module: 'dms' },
  { prefix: '/qms/audit', module: 'audit' },
  { prefix: '/qms/vendors', module: 'vendors' },
  { prefix: '/qms/validation', module: 'validation' },
  { prefix: '/qms/csv', module: 'csv' },
  { prefix: '/qms/equipment', module: 'equipment' },
  { prefix: '/qms/monitoring', module: 'monitoring' },
  { prefix: '/qms/warehouse', module: 'warehouse' },
  { prefix: '/qms/ebmr', module: 'ebmr' },
  { prefix: '/qms', module: 'qms' },
];

export function resolveModuleFromPath(pathname: string): AppModule | null {
  const match = ROUTE_MODULE_MAP.find(({ prefix }) =>
    pathname === prefix || pathname.startsWith(`${prefix}/`),
  );
  return match?.module ?? null;
}

export function navHrefModule(href: string): AppModule | null {
  if (href === '/dashboard') return 'qms';
  return resolveModuleFromPath(href);
}
