import { z } from 'zod';
import {
  ADMIN_MODULES, PERMISSION_ACTIONS, PARAMETER_TYPES, RESULT_TYPES,
  USER_STATUSES, RECORD_STATUSES, NOTIFICATION_EVENTS, SIGNATURE_MEANINGS,
  BACKUP_STATUSES, LOGIN_STATUSES, ACCESS_REVIEW_STATUSES, TEMPLATE_TYPES,
  TEMPLATE_CATEGORIES, TEMPLATE_LANGUAGES, TEMPLATE_APPROVAL_STATUSES,
  SYSTEM_ENVIRONMENTS, MODULE_LICENSE_STATUSES,
  MODULE_FEATURE_STATUSES, MODULE_VISIBILITY_STATUSES,
  MASTER_DATA_IMPORT_MODES, MASTER_DATA_EXPORT_FORMATS, MASTER_DATA_OPERATION_STATUSES,
  ROLE_MATRIX_MODULES, ROLE_MATRIX_ACTIONS, DATA_SCOPE_OPTIONS, FIELD_ACCESS_LEVELS,
  DEPARTMENT_TYPES, DESIGNATION_LEVELS, EMPLOYMENT_CATEGORIES, JOB_BANDS, JOB_GRADES, REPORTING_LEVELS,
  SITE_TYPES, COMPANY_TYPES, INDUSTRIES, DATE_FORMATS, TIME_FORMATS, CURRENCY_OPTIONS, TIMEZONE_OPTIONS,
  DOSAGE_FORMS, ROUTE_OPTIONS, MARKET_OPTIONS, PRODUCT_STATUSES,
  PRODUCT_LIFECYCLE_STATUSES, PRODUCT_CATEGORIES, PACK_TYPES, CONTAINER_CLOSURE_TYPES,
  INGREDIENT_TYPES, PACKING_MATERIAL_TYPES, PRODUCT_ATTACHMENT_TYPES,
  BATCH_STATUSES, RELEASE_STATUSES, BATCH_SIZE_UNITS, QC_STATUSES, QA_STATUSES,
  PARAMETER_CATEGORIES, PARAMETER_GROUPS, PARAMETER_MODULE_OPTIONS,
  PARAMETER_DATA_TYPES, PARAMETER_CALCULATION_TYPES,
  PROCESS_STAGES, CRITICALITY_OPTIONS, FREQUENCY_OPTIONS,
  WORKFLOW_MODULE_OPTIONS, WORKFLOW_TYPES, WORKFLOW_STEP_TYPES, APPROVAL_WORKFLOW_TYPES,
  APPROVAL_MATRIX_MODULES, RISK_LEVELS, APPROVAL_MODES, APPROVAL_MATRIX_PRIORITIES,
  DOCUMENT_NUMBERING_MODULES, DOCUMENT_TYPE_OPTIONS,
  NUMBERING_YEAR_FORMATS, NUMBERING_MONTH_FORMATS, NUMBERING_SEPARATOR_OPTIONS,
  NUMBERING_RESET_FREQUENCIES, REVISION_FORMAT_OPTIONS, FORMAT_TOKENS,
  AUDIT_TRAIL_MODULES, AUDIT_ACTION_TYPES, AUDIT_LOG_STATUSES,
  ESIGN_SETTING_MODULES, ESIGN_ACTION_TYPES, ESIGN_SIGNATURE_MEANINGS,
  NOTIFICATION_MODULES, NOTIFICATION_EVENT_TRIGGERS, NOTIFICATION_CHANNEL_TYPES,
  NOTIFICATION_PRIORITIES, REMINDER_FREQUENCIES,
  BACKUP_TYPES, BACKUP_SCOPES, BACKUP_FREQUENCIES,
  RESTORE_TYPES, RESTORE_STATUSES, BACKUP_EXPORT_COLLECTIONS,
  FINANCIAL_YEAR_MONTHS, SIDEBAR_MODES, LOGO_DISPLAY_MODES,
} from './constants';

const baseFields = {
  id: z.string().optional(),
  createdBy: z.string().default(''),
  createdAt: z.string().optional(),
  updatedBy: z.string().default(''),
  updatedAt: z.string().optional(),
  status: z.enum(RECORD_STATUSES).default('Active'),
};

const phoneSchema = z.string()
  .regex(/^$|^\+?[\d\s\-()]{10,15}$/, 'Enter a valid phone number (10–15 digits)')
  .default('');

export const adminUserSchema = z.object({
  ...baseFields,
  userId: z.string().optional(),
  employeeId: z.string().trim().min(1, 'Employee ID is required').max(80),
  employeeCode: z.string().trim().max(80).default(''),
  firstName: z.string().trim().max(100).default(''),
  middleName: z.string().trim().max(100).default(''),
  lastName: z.string().trim().max(100).default(''),
  fullName: z.string().trim().min(1, 'Full name is required').max(200),
  email: z.string().trim().min(1, 'Email is required').email('Valid email required').max(320),
  mobileNumber: phoneSchema,
  alternateMobile: phoneSchema,
  username: z.string()
    .trim()
    .max(80)
    .regex(/^$|^[a-zA-Z0-9._-]+$/, 'Username may contain letters, numbers, dots, underscores, and hyphens')
    .default(''),
  department: z.string().trim().min(1, 'Department is required').max(160),
  designation: z.string().trim().max(160).default(''),
  role: z.string().trim().min(1, 'Role is required').max(80),
  reportingManager: z.string().trim().max(200).default(''),
  managerId: z.string().trim().max(128).default(''),
  businessUnit: z.string().trim().max(160).default(''),
  siteId: z.string().trim().max(128).default(''),
  siteName: z.string().trim().max(200).default(''),
  location: z.string().trim().max(240).default(''),
  shift: z.string().trim().max(80).default(''),
  employmentType: z.enum(['Permanent', 'Contract', 'Temporary', 'Consultant', 'Vendor', 'Intern']).default('Permanent'),
  gender: z.enum(['', 'Female', 'Male', 'Non-binary', 'Prefer not to say']).default(''),
  dateOfBirth: z.string().default(''),
  userStatus: z.enum(USER_STATUSES).or(z.literal('Pending Approval')).default('Active'),
  statusBeforeLock: z.enum(['Active', 'Inactive', 'Suspended', 'Pending Approval']).optional(),
  accountLocked: z.boolean().default(false),
  profilePhoto: z.string()
    .url('Profile picture must be a valid URL')
    .refine((value) => value.startsWith('https://'), 'Profile picture URL must use HTTPS')
    .or(z.literal(''))
    .default(''),
  joiningDate: z.string().default(''),
  remarks: z.string().trim().max(2000).default(''),
  passwordResetRequired: z.boolean().default(false),
  twoFactorEnabled: z.boolean().default(false),
  lastLogin: z.string().nullable().default(null),
  emailVerified: z.boolean().default(false),
  authUid: z.string().optional(),
  isDeleted: z.boolean().optional(),
}).refine(
  (data) => !data.dateOfBirth || data.dateOfBirth < new Date().toISOString().slice(0, 10),
  { message: 'Date of birth must be in the past', path: ['dateOfBirth'] },
).refine(
  (data) => !data.managerId || data.managerId !== data.id && data.managerId !== data.authUid,
  { message: 'A user cannot report to themselves', path: ['managerId'] },
);

export const adminUserCreateSchema = adminUserSchema.and(z.object({
  temporaryPassword: z.string()
    .min(12, 'Password must be at least 12 characters')
    .max(128)
    .regex(/[A-Z]/, 'Password must include an uppercase letter')
    .regex(/[a-z]/, 'Password must include a lowercase letter')
    .regex(/\d/, 'Password must include a number')
    .regex(/[^A-Za-z0-9]/, 'Password must include a special character')
    .optional(),
}));

const matrixPermissionsSchema = z.record(
  z.string(),
  z.record(z.string(), z.boolean()),
);

const fieldPolicySchema = z.object({
  fieldKey: z.string().min(1).max(120),
  access: z.enum(FIELD_ACCESS_LEVELS).default('Editable'),
  modules: z.array(z.string()).default([]),
  condition: z.string().max(500).default(''),
});

export const roleSchema = z.object({
  ...baseFields,
  roleId: z.string().min(1, 'Role ID is required'),
  roleName: z.string().min(1, 'Role name is required'),
  roleDescription: z.string().default(''),
  description: z.string().default(''),
  roleLevel: z.coerce.number().min(1).max(100).default(10),
  level: z.coerce.number().min(1).max(100).default(10),
  departmentAccess: z.string().default(''),
  siteAccess: z.string().default(''),
  businessUnitAccess: z.string().default(''),
  dataScope: z.enum(DATA_SCOPE_OPTIONS).default('Organization Records'),
  fieldPolicies: z.array(fieldPolicySchema).default([]),
  isSystemRole: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
  changeReason: z.string().optional(),
});

export const permissionMatrixSchema = z.object({
  ...baseFields,
  roleId: z.string().min(1),
  roleName: z.string().min(1),
  permissions: matrixPermissionsSchema,
  isDeleted: z.boolean().optional(),
});

export const roleFormSchema = z.object({
  roleId: z.string().min(1, 'Role ID is required')
    .regex(/^[a-z][a-z0-9_]{1,63}$/, 'Role ID must be lowercase snake_case (2–64 chars)'),
  roleName: z.string().min(1, 'Role name is required').max(120),
  roleDescription: z.string().max(2000).default(''),
  roleLevel: z.coerce.number().min(1).max(100).default(10),
  departmentAccess: z.string().default(''),
  siteAccess: z.string().default(''),
  businessUnitAccess: z.string().default(''),
  dataScope: z.enum(DATA_SCOPE_OPTIONS).default('Organization Records'),
  fieldPolicies: z.array(fieldPolicySchema).max(100).default([]),
  status: z.enum(RECORD_STATUSES).default('Active'),
  permissions: matrixPermissionsSchema,
  changeReason: z.string().trim().min(5, 'Change reason is required (min 5 characters)').max(500),
}).refine(
  (data) => Object.values(data.permissions).some((mod) => Object.values(mod).some(Boolean)),
  { message: 'At least one module permission is required', path: ['permissions'] },
);

export const departmentSchema = z.object({
  ...baseFields,
  departmentId: z.string().default(''),
  departmentCode: z.string().min(1, 'Department code is required'),
  departmentName: z.string().min(1, 'Department name is required'),
  shortName: z.string().default(''),
  departmentType: z.enum(DEPARTMENT_TYPES).default('Other'),
  parentDepartmentId: z.string().default(''),
  parentDepartmentName: z.string().default(''),
  departmentHead: z.string().default(''),
  departmentHeadId: z.string().default(''),
  manager: z.string().default(''),
  managerId: z.string().default(''),
  hodEmail: z.string().email('Valid HOD email required').or(z.literal('')).default(''),
  email: z.string().email('Valid email required').or(z.literal('')).default(''),
  phone: z.string().default(''),
  extension: z.string().default(''),
  businessUnit: z.string().default(''),
  siteId: z.string().default(''),
  siteLocation: z.string().default(''),
  location: z.string().default(''),
  costCenter: z.string().default(''),
  description: z.string().default(''),
  remarks: z.string().default(''),
  isSystemDepartment: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
});

export const departmentFormSchema = z.object({
  departmentCode: z.string().min(1, 'Department code is required')
    .max(32)
    .regex(/^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$/, 'Code must be alphanumeric (optional _ or -)'),
  departmentName: z.string().min(1, 'Department name is required').max(160),
  shortName: z.string().max(40).default(''),
  departmentType: z.enum(DEPARTMENT_TYPES, { required_error: 'Department type is required' }),
  parentDepartmentId: z.string().default(''),
  departmentHead: z.string().min(1, 'Department head must be selected from active users'),
  departmentHeadId: z.string().default(''),
  manager: z.string().default(''),
  managerId: z.string().default(''),
  hodEmail: z.string().email('Valid HOD email required').or(z.literal('')).default(''),
  email: z.string().email('Valid email required').or(z.literal('')).default(''),
  phone: z.string().max(40).default(''),
  extension: z.string().max(20).default(''),
  businessUnit: z.string().max(160).default(''),
  siteId: z.string().default(''),
  siteLocation: z.string().default(''),
  location: z.string().max(200).default(''),
  costCenter: z.string().max(64).default(''),
  description: z.string().max(2000).default(''),
  remarks: z.string().max(2000).default(''),
  status: z.enum(RECORD_STATUSES).default('Active'),
  changeReason: z.string().trim().min(5, 'Change reason is required (min 5 characters)').max(500),
});

export const designationSchema = z.object({
  ...baseFields,
  designationId: z.string().default(''),
  designationCode: z.string().min(1, 'Designation code is required'),
  designationName: z.string().min(1, 'Designation name is required'),
  shortName: z.string().default(''),
  department: z.string().min(1, 'Department is required'),
  parentDesignationId: z.string().default(''),
  parentDesignationName: z.string().default(''),
  designationLevel: z.enum(DESIGNATION_LEVELS).default('Executive'),
  reportingLevel: z.enum(REPORTING_LEVELS).or(z.literal('')).default(''),
  jobGrade: z.enum(JOB_GRADES).or(z.literal('')).default(''),
  jobBand: z.enum(JOB_BANDS).or(z.literal('')).default(''),
  jobLevel: z.string().default(''),
  employmentCategory: z.enum(EMPLOYMENT_CATEGORIES).default('Permanent'),
  minimumExperience: z.coerce.number().min(0).max(50).default(0),
  requiredQualification: z.string().default(''),
  requiredSkills: z.string().default(''),
  businessUnit: z.string().default(''),
  siteId: z.string().default(''),
  siteName: z.string().default(''),
  approvalLevel: z.coerce.number().min(1).max(10).default(1),
  approvalAuthority: z.boolean().default(false),
  canReview: z.boolean().default(false),
  canApprove: z.boolean().default(false),
  canESign: z.boolean().default(false),
  description: z.string().default(''),
  remarks: z.string().default(''),
  isSystemDesignation: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
});

export const designationFormSchema = z.object({
  designationCode: z.string().min(1, 'Designation code is required')
    .max(32)
    .regex(/^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$/, 'Code must be alphanumeric (optional _ or -)'),
  designationName: z.string().min(1, 'Designation name is required').max(160),
  shortName: z.string().max(40).default(''),
  department: z.string().min(1, 'Department is required'),
  parentDesignationId: z.string().default(''),
  designationLevel: z.enum(DESIGNATION_LEVELS, { required_error: 'Designation level is required' }),
  reportingLevel: z.enum(REPORTING_LEVELS).or(z.literal('')).default(''),
  jobGrade: z.enum(JOB_GRADES).or(z.literal('')).default(''),
  jobBand: z.enum(JOB_BANDS).or(z.literal('')).default(''),
  jobLevel: z.string().max(40).default(''),
  employmentCategory: z.enum(EMPLOYMENT_CATEGORIES).default('Permanent'),
  minimumExperience: z.coerce.number().min(0).max(50).default(0),
  requiredQualification: z.string().max(500).default(''),
  requiredSkills: z.string().max(1000).default(''),
  businessUnit: z.string().max(160).default(''),
  siteId: z.string().default(''),
  siteName: z.string().default(''),
  approvalAuthority: z.boolean().default(false),
  canReview: z.boolean().default(false),
  canApprove: z.boolean().default(false),
  canESign: z.boolean().default(false),
  description: z.string().max(2000).default(''),
  remarks: z.string().max(2000).default(''),
  status: z.enum(RECORD_STATUSES).default('Active'),
  changeReason: z.string().trim().min(5, 'Change reason is required (min 5 characters)').max(500),
});

export const companySiteSchema = z.object({
  ...baseFields,
  companyId: z.string().default(''),
  companyName: z.string().min(1, 'Company name is required'),
  companyCode: z.string().default(''),
  legalName: z.string().default(''),
  shortName: z.string().default(''),
  companyType: z.enum(COMPANY_TYPES).or(z.literal('')).default(''),
  industry: z.enum(INDUSTRIES).or(z.literal('')).default(''),
  registrationNumber: z.string().default(''),
  panNumber: z.string().default(''),
  licenseNumber: z.string().default(''),
  companyEmail: z.string().email('Valid company email required').or(z.literal('')).default(''),
  companyPhone: z.string().default(''),
  companyLogo: z.string().default(''),
  siteRecordId: z.string().default(''),
  siteName: z.string().min(1, 'Site name is required'),
  siteCode: z.string().default(''),
  siteType: z.enum(SITE_TYPES).default('Manufacturing Plant'),
  businessUnit: z.string().default(''),
  isManufacturingUnit: z.boolean().default(false),
  isWarehouse: z.boolean().default(false),
  isLaboratory: z.boolean().default(false),
  isOffice: z.boolean().default(false),
  plantName: z.string().default(''),
  plantCode: z.string().default(''),
  plantAddress: z.string().default(''),
  siteAddress: z.string().default(''),
  city: z.string().default(''),
  state: z.string().default(''),
  country: z.string().default(''),
  pinZipCode: z.string().default(''),
  gstNumber: z.string().default(''),
  gstNo: z.string().default(''),
  manufacturingLicenseNumber: z.string().default(''),
  drugLicenseNumber: z.string().default(''),
  licenseNo: z.string().default(''),
  contactPerson: z.string().default(''),
  contactEmail: z.string().email('Valid contact email required').or(z.literal('')).default(''),
  contactPhone: z.string().default(''),
  contactNumber: z.string().default(''),
  siteHead: z.string().default(''),
  siteHeadId: z.string().default(''),
  qualityHead: z.string().default(''),
  qualityHeadId: z.string().default(''),
  website: z.string().default(''),
  timezone: z.string().default('Asia/Kolkata'),
  defaultTimezone: z.string().default('Asia/Kolkata'),
  dateFormat: z.enum(DATE_FORMATS).default('DD/MM/YYYY'),
  timeFormat: z.enum(TIME_FORMATS).default('24h'),
  defaultCurrency: z.enum(CURRENCY_OPTIONS).default('INR'),
  documentHeaderFormat: z.string().default(''),
  documentFooterText: z.string().default(''),
  remarks: z.string().max(2000).default(''),
  isDefault: z.boolean().default(false),
  isSystemSite: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
});

export const companySiteFormSchema = z.object({
  companyName: z.string().min(1, 'Company name is required'),
  companyCode: z.string().min(1, 'Company code is required').max(32),
  legalName: z.string().max(200).default(''),
  shortName: z.string().max(40).default(''),
  companyType: z.enum(COMPANY_TYPES).or(z.literal('')).default(''),
  industry: z.enum(INDUSTRIES).or(z.literal('')).default(''),
  registrationNumber: z.string().max(80).default(''),
  panNumber: z.string().max(20).default(''),
  licenseNumber: z.string().max(80).default(''),
  companyEmail: z.string().email('Valid company email required').or(z.literal('')).default(''),
  companyPhone: z.string().default(''),
  siteName: z.string().min(1, 'Site name is required'),
  siteCode: z.string().min(1, 'Site code is required').max(32),
  siteType: z.enum(SITE_TYPES).default('Manufacturing Plant'),
  businessUnit: z.string().max(160).default(''),
  isManufacturingUnit: z.boolean().default(false),
  isWarehouse: z.boolean().default(false),
  isLaboratory: z.boolean().default(false),
  isOffice: z.boolean().default(false),
  plantName: z.string().default(''),
  plantCode: z.string().default(''),
  plantAddress: z.string().min(1, 'Site address is required'),
  city: z.string().default(''),
  state: z.string().default(''),
  country: z.string().default('India'),
  pinZipCode: z.string().default(''),
  gstNumber: z.string().default(''),
  manufacturingLicenseNumber: z.string().default(''),
  drugLicenseNumber: z.string().default(''),
  contactPerson: z.string().default(''),
  contactEmail: z.string().email('Valid contact email required').or(z.literal('')).default(''),
  contactPhone: z.string().default(''),
  siteHead: z.string().default(''),
  siteHeadId: z.string().default(''),
  qualityHead: z.string().default(''),
  qualityHeadId: z.string().default(''),
  website: z.string().default(''),
  timezone: z.string().default('Asia/Kolkata'),
  dateFormat: z.enum(DATE_FORMATS).default('DD/MM/YYYY'),
  timeFormat: z.enum(TIME_FORMATS).default('24h'),
  defaultCurrency: z.enum(CURRENCY_OPTIONS).default('INR'),
  documentHeaderFormat: z.string().default(''),
  documentFooterText: z.string().default(''),
  remarks: z.string().max(2000).default(''),
  status: z.enum(RECORD_STATUSES).default('Active'),
  isDefault: z.boolean().default(false),
  changeReason: z.string().trim().min(5, 'Change reason is required (min 5 characters)').max(500),
});

export const productCompositionRowSchema = z.object({
  id: z.string().optional(),
  ingredientName: z.string().min(1, 'Ingredient name required'),
  ingredientType: z.enum(INGREDIENT_TYPES),
  grade: z.string().default(''),
  quantity: z.coerce.number().positive('Quantity must be numeric'),
  unit: z.string().default(''),
  functionPurpose: z.string().default(''),
  specificationNo: z.string().default(''),
  stpNo: z.string().default(''),
});

export const productPackingRowSchema = z.object({
  id: z.string().optional(),
  packingMaterial: z.string().min(1, 'Packing material required'),
  materialType: z.enum(PACKING_MATERIAL_TYPES),
  packSize: z.string().default(''),
  quantity: z.coerce.number().min(0, 'Quantity must be numeric').default(0),
  unit: z.string().default(''),
  specificationNo: z.string().default(''),
  stpNo: z.string().default(''),
});

export const adminProductSchema = z.object({
  ...baseFields,
  productId: z.string().default(''),
  productCode: z.string().min(1, 'Product code is required'),
  productName: z.string().min(1, 'Product name is required'),
  genericName: z.string().default(''),
  brandName: z.string().default(''),
  productFamily: z.string().default(''),
  category: z.string().default(''),
  therapeuticCategory: z.string().default(''),
  strength: z.string().default(''),
  dosageForm: z.string().default(''),
  routeOfAdministration: z.string().default(''),
  packSize: z.string().default(''),
  packType: z.enum(PACK_TYPES).or(z.literal('')).default(''),
  containerClosure: z.enum(CONTAINER_CLOSURE_TYPES).or(z.literal('')).default(''),
  market: z.string().default(''),
  country: z.string().default(''),
  manufacturingSite: z.string().default(''),
  businessUnit: z.string().default(''),
  department: z.string().default(''),
  productOwner: z.string().default(''),
  lifecycleStatus: z.enum(PRODUCT_LIFECYCLE_STATUSES).default('Commercial'),
  shelfLife: z.string().default(''),
  storageCondition: z.string().default(''),
  standardBatchSize: z.string().default(''),
  batchSize: z.string().default(''),
  batchPrefix: z.string().default(''),
  manufacturingLicenseNo: z.string().default(''),
  manufacturingLicenseNumber: z.string().default(''),
  registrationNumber: z.string().default(''),
  licenseNumber: z.string().default(''),
  mfrNumber: z.string().default(''),
  bmrNumber: z.string().default(''),
  bprNumber: z.string().default(''),
  specificationNumber: z.string().default(''),
  stpNumber: z.string().default(''),
  hsnCode: z.string().default(''),
  gtin: z.string().default(''),
  barcode: z.string().default(''),
  qrCode: z.string().default(''),
  productStatus: z.enum(PRODUCT_STATUSES).default('Active'),
  description: z.string().max(4000).default(''),
  remarks: z.string().default(''),
  composition: z.string().default(''),
  packingStyle: z.string().default(''),
  isArchived: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
});

export const productFormSchema = z.object({
  productCode: z.string().min(1, 'Product code is required'),
  productName: z.string().min(1, 'Product name is required'),
  genericName: z.string().min(1, 'Generic name is required'),
  brandName: z.string().default(''),
  productFamily: z.string().default(''),
  category: z.enum(PRODUCT_CATEGORIES).or(z.literal('')).default(''),
  strength: z.string().min(1, 'Strength is required'),
  dosageForm: z.enum(DOSAGE_FORMS, { required_error: 'Dosage form is required' }),
  routeOfAdministration: z.string().default(''),
  packSize: z.string().default(''),
  packType: z.enum(PACK_TYPES).or(z.literal('')).default(''),
  containerClosure: z.enum(CONTAINER_CLOSURE_TYPES).or(z.literal('')).default(''),
  market: z.enum(MARKET_OPTIONS).default('Domestic'),
  country: z.string().default('India'),
  manufacturingSite: z.string().default(''),
  businessUnit: z.string().default(''),
  department: z.string().default(''),
  productOwner: z.string().default(''),
  lifecycleStatus: z.enum(PRODUCT_LIFECYCLE_STATUSES).default('Commercial'),
  therapeuticCategory: z.string().default(''),
  shelfLife: z.string().min(1, 'Shelf life is required').refine((v) => /^\d+/.test(v.trim()), 'Shelf life must be numeric'),
  storageCondition: z.string().default(''),
  standardBatchSize: z.string().default(''),
  manufacturingLicenseNumber: z.string().default(''),
  registrationNumber: z.string().default(''),
  licenseNumber: z.string().default(''),
  mfrNumber: z.string().default(''),
  bmrNumber: z.string().default(''),
  bprNumber: z.string().default(''),
  specificationNumber: z.string().default(''),
  stpNumber: z.string().default(''),
  batchPrefix: z.string().default(''),
  hsnCode: z.string().default(''),
  gtin: z.string().default(''),
  barcode: z.string().default(''),
  qrCode: z.string().default(''),
  productStatus: z.enum(PRODUCT_STATUSES).default('Active'),
  description: z.string().max(4000).default(''),
  remarks: z.string().default(''),
  compositions: z.array(productCompositionRowSchema).default([]),
  packingDetails: z.array(productPackingRowSchema).default([]),
  changeReason: z.string().trim().min(5, 'Change reason is required (min 5 characters)').max(500),
}).refine(
  (data) => data.compositions.some((c) => c.ingredientType === 'API'),
  { message: 'At least one API ingredient is required', path: ['compositions'] },
);

export const productAttachmentSchema = z.object({
  id: z.string().optional(),
  productId: z.string(),
  fileName: z.string(),
  fileType: z.string(),
  fileSize: z.number(),
  attachmentType: z.enum(PRODUCT_ATTACHMENT_TYPES),
  storagePath: z.string(),
  downloadUrl: z.string(),
  uploadedBy: z.string().default(''),
  uploadedAt: z.string().optional(),
});

export const adminBatchSchema = z.object({
  ...baseFields,
  batchId: z.string().default(''),
  batchNumber: z.string().min(1, 'Batch number is required'),
  batchCode: z.string().default(''),
  productCode: z.string().min(1, 'Product is required'),
  productName: z.string().default(''),
  productVersion: z.string().default(''),
  productCategory: z.string().default(''),
  genericName: z.string().default(''),
  strength: z.string().default(''),
  dosageForm: z.string().default(''),
  market: z.string().default(''),
  manufacturingOrder: z.string().default(''),
  batchSize: z.string().default(''),
  batchSizeUnit: z.string().default(''),
  unit: z.string().default(''),
  plannedQuantity: z.string().default(''),
  actualQuantity: z.string().default(''),
  manufacturingDate: z.string().default(''),
  packagingDate: z.string().default(''),
  expiryDate: z.string().default(''),
  retestDate: z.string().default(''),
  shelfLife: z.string().default(''),
  batchPrefix: z.string().default(''),
  manufacturingSite: z.string().default(''),
  businessUnit: z.string().default(''),
  department: z.string().default(''),
  warehouse: z.string().default(''),
  storageLocation: z.string().default(''),
  manufacturingLine: z.string().default(''),
  lineNumber: z.string().default(''),
  equipment: z.string().default(''),
  processVersion: z.string().default(''),
  recipeVersion: z.string().default(''),
  shift: z.string().default(''),
  mfrNumber: z.string().default(''),
  bmrNumber: z.string().default(''),
  bprNumber: z.string().default(''),
  manufacturedFor: z.string().default(''),
  customerName: z.string().default(''),
  batchStatus: z.enum(BATCH_STATUSES).default('Planned'),
  releaseStatus: z.enum(RELEASE_STATUSES).default('Pending'),
  qcStatus: z.enum(QC_STATUSES).default('Pending'),
  qaStatus: z.enum(QA_STATUSES).default('Pending'),
  releaseDate: z.string().default(''),
  qaReleasedBy: z.string().default(''),
  semiFinishedBatchNumber: z.string().default(''),
  finishedProductBatchNumber: z.string().default(''),
  packingBatchNumber: z.string().default(''),
  statusChangeReason: z.string().default(''),
  remarks: z.string().default(''),
  isArchived: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
  deletedAt: z.string().optional(),
  deletedBy: z.string().optional(),
});

export const batchFormSchema = z.object({
  productCode: z.string().min(1, 'Product is required'),
  batchNumber: z.string().default(''),
  autoGenerateBatchNumber: z.boolean().optional(),
  batchCode: z.string().default(''),
  productName: z.string().default(''),
  productVersion: z.string().default(''),
  productCategory: z.string().default(''),
  genericName: z.string().default(''),
  strength: z.string().default(''),
  dosageForm: z.string().default(''),
  market: z.string().default(''),
  manufacturingOrder: z.string().default(''),
  batchSize: z.coerce.number().positive('Batch size must be numeric'),
  batchSizeUnit: z.enum(BATCH_SIZE_UNITS).default('Vials'),
  plannedQuantity: z.coerce.number().optional(),
  actualQuantity: z.coerce.number().optional(),
  manufacturingDate: z.string().min(1, 'Manufacturing date is required'),
  packagingDate: z.string().default(''),
  expiryDate: z.string().min(1, 'Expiry date is required'),
  retestDate: z.string().default(''),
  shelfLife: z.string().default(''),
  batchPrefix: z.string().default(''),
  manufacturingSite: z.string().default(''),
  businessUnit: z.string().default(''),
  department: z.string().default(''),
  warehouse: z.string().default(''),
  storageLocation: z.string().default(''),
  manufacturingLine: z.string().default(''),
  equipment: z.string().default(''),
  processVersion: z.string().default(''),
  recipeVersion: z.string().default(''),
  shift: z.string().default(''),
  mfrNumber: z.string().default(''),
  bmrNumber: z.string().default(''),
  bprNumber: z.string().default(''),
  manufacturedFor: z.string().default(''),
  customerName: z.string().default(''),
  batchStatus: z.enum(BATCH_STATUSES).default('Planned'),
  releaseStatus: z.enum(RELEASE_STATUSES).default('Pending'),
  qcStatus: z.enum(QC_STATUSES).default('Pending'),
  qaStatus: z.enum(QA_STATUSES).default('Pending'),
  releaseDate: z.string().default(''),
  qaReleasedBy: z.string().default(''),
  semiFinishedBatchNumber: z.string().default(''),
  finishedProductBatchNumber: z.string().default(''),
  packingBatchNumber: z.string().default(''),
  statusChangeReason: z.string().default(''),
  remarks: z.string().default(''),
  changeReason: z.string().trim().max(500).default(''),
  qaOverride: z.boolean().optional(),
}).refine(
  (data) => !data.manufacturingDate || !data.expiryDate || data.expiryDate >= data.manufacturingDate,
  { message: 'Expiry date must be on or after manufacturing date', path: ['expiryDate'] },
).refine(
  (data) => !data.packagingDate || !data.manufacturingDate || data.packagingDate >= data.manufacturingDate,
  { message: 'Packaging date must be on or after manufacturing date', path: ['packagingDate'] },
).refine(
  (data) => data.autoGenerateBatchNumber || data.batchNumber.trim().length > 0,
  { message: 'Batch number is required', path: ['batchNumber'] },
).refine(
  (data) => data.batchStatus !== 'Rejected' || data.statusChangeReason.trim().length > 0,
  { message: 'Rejection reason is required', path: ['statusChangeReason'] },
).refine(
  (data) => data.batchStatus !== 'Hold' || data.statusChangeReason.trim().length > 0,
  { message: 'Hold reason is required', path: ['statusChangeReason'] },
);

export const batchAttachmentSchema = z.object({
  id: z.string().optional(),
  batchId: z.string(),
  fileName: z.string(),
  fileType: z.string(),
  fileSize: z.number(),
  storagePath: z.string(),
  downloadUrl: z.string(),
  uploadedBy: z.string().default(''),
  uploadedAt: z.string().optional(),
});

export const parameterSchema = z.object({
  ...baseFields,
  parameterId: z.string().default(''),
  parameterCode: z.string().min(1, 'Parameter code is required'),
  parameterName: z.string().min(1, 'Parameter name is required'),
  shortName: z.string().default(''),
  description: z.string().default(''),
  parameterType: z.enum(PARAMETER_TYPES),
  parameterCategory: z.string().default(''),
  parameterGroup: z.string().default(''),
  moduleName: z.string().default(''),
  subModule: z.string().default(''),
  productLink: z.string().default(''),
  product: z.string().default(''),
  productCategory: z.string().default(''),
  processStage: z.string().default(''),
  department: z.string().default(''),
  testMethodStp: z.string().default(''),
  specificationNo: z.string().default(''),
  targetValue: z.string().default(''),
  target: z.string().default(''),
  lowerLimit: z.string().default(''),
  lsl: z.string().default(''),
  upperLimit: z.string().default(''),
  usl: z.string().default(''),
  alertLimitLow: z.string().default(''),
  alertLimitHigh: z.string().default(''),
  actionLimitLow: z.string().default(''),
  actionLimitHigh: z.string().default(''),
  criticalLimit: z.string().default(''),
  defaultValue: z.string().default(''),
  precision: z.string().default(''),
  formula: z.string().default(''),
  dataType: z.enum(PARAMETER_DATA_TYPES).default('Numeric'),
  calculationType: z.enum(PARAMETER_CALCULATION_TYPES).default('Manual'),
  unit: z.string().default(''),
  resultType: z.enum(RESULT_TYPES),
  frequency: z.string().default(''),
  criticality: z.string().default(''),
  mandatory: z.boolean().default(false),
  displayOrder: z.coerce.number().optional(),
  sequenceNumber: z.string().default(''),
  applicableSite: z.string().default(''),
  businessUnit: z.string().default(''),
  ootApplicable: z.boolean().default(false),
  oosApplicable: z.boolean().default(false),
  autoDeviationRequired: z.boolean().default(false),
  autoCapaRequired: z.boolean().default(false),
  remarks: z.string().default(''),
  isArchived: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
  deletedAt: z.string().optional(),
  deletedBy: z.string().optional(),
});

const numericLimit = (val: string) => val.trim() !== '' && !Number.isNaN(Number(val));

export const parameterFormSchema = z.object({
  parameterCode: z.string().min(1, 'Parameter code is required'),
  parameterName: z.string().min(1, 'Parameter name is required'),
  shortName: z.string().default(''),
  description: z.string().default(''),
  parameterType: z.enum(PARAMETER_TYPES),
  parameterCategory: z.enum(PARAMETER_CATEGORIES).default('Manufacturing'),
  parameterGroup: z.enum(PARAMETER_GROUPS).default('General'),
  moduleName: z.enum(PARAMETER_MODULE_OPTIONS).default('General'),
  subModule: z.string().default(''),
  productLink: z.string().default(''),
  productCategory: z.string().default(''),
  processStage: z.enum(PROCESS_STAGES).default('Mixing'),
  department: z.string().default(''),
  testMethodStp: z.string().default(''),
  specificationNo: z.string().default(''),
  targetValue: z.string().default(''),
  lowerLimit: z.string().default(''),
  upperLimit: z.string().default(''),
  alertLimitLow: z.string().default(''),
  alertLimitHigh: z.string().default(''),
  actionLimitLow: z.string().default(''),
  actionLimitHigh: z.string().default(''),
  criticalLimit: z.string().default(''),
  defaultValue: z.string().default(''),
  precision: z.string().default(''),
  formula: z.string().default(''),
  dataType: z.enum(PARAMETER_DATA_TYPES).default('Numeric'),
  calculationType: z.enum(PARAMETER_CALCULATION_TYPES).default('Manual'),
  unit: z.string().default(''),
  resultType: z.enum(RESULT_TYPES),
  frequency: z.enum(FREQUENCY_OPTIONS).default('Per Batch'),
  criticality: z.enum(CRITICALITY_OPTIONS).default('Major'),
  mandatory: z.boolean().default(false),
  displayOrder: z.coerce.number().optional(),
  sequenceNumber: z.string().default(''),
  applicableSite: z.string().default(''),
  businessUnit: z.string().default(''),
  ootApplicable: z.boolean().default(false),
  oosApplicable: z.boolean().default(false),
  autoDeviationRequired: z.boolean().default(false),
  autoCapaRequired: z.boolean().default(false),
  remarks: z.string().default(''),
  changeReason: z.string().trim().max(500).default(''),
}).refine(
  (data) => data.resultType !== 'Numeric' || data.unit.trim().length > 0,
  { message: 'Unit is required for numeric parameters', path: ['unit'] },
).refine(
  (data) => data.resultType !== 'Numeric' || (numericLimit(data.lowerLimit) && numericLimit(data.upperLimit)),
  { message: 'Lower and upper limits are required for numeric parameters', path: ['lowerLimit'] },
).refine(
  (data) => {
    if (data.resultType !== 'Numeric') return true;
    if (!numericLimit(data.lowerLimit) || !numericLimit(data.upperLimit)) return true;
    return Number(data.upperLimit) > Number(data.lowerLimit);
  },
  { message: 'Upper limit must be greater than lower limit', path: ['upperLimit'] },
).refine(
  (data) => {
    if (data.resultType !== 'Numeric' || !numericLimit(data.alertLimitLow)) return true;
    if (!numericLimit(data.lowerLimit)) return true;
    return Number(data.alertLimitLow) >= Number(data.lowerLimit);
  },
  { message: 'Alert limit low must be within specification limits', path: ['alertLimitLow'] },
).refine(
  (data) => {
    if (data.resultType !== 'Numeric' || !numericLimit(data.alertLimitHigh)) return true;
    if (!numericLimit(data.upperLimit)) return true;
    return Number(data.alertLimitHigh) <= Number(data.upperLimit);
  },
  { message: 'Alert limit high must be within specification limits', path: ['alertLimitHigh'] },
).refine(
  (data) => {
    if (data.resultType !== 'Numeric' || !numericLimit(data.actionLimitLow)) return true;
    if (!numericLimit(data.lowerLimit)) return true;
    return Number(data.actionLimitLow) >= Number(data.lowerLimit);
  },
  { message: 'Action limit low must be within specification limits', path: ['actionLimitLow'] },
).refine(
  (data) => {
    if (data.resultType !== 'Numeric' || !numericLimit(data.actionLimitHigh)) return true;
    if (!numericLimit(data.upperLimit)) return true;
    return Number(data.actionLimitHigh) <= Number(data.upperLimit);
  },
  { message: 'Action limit high must be within specification limits', path: ['actionLimitHigh'] },
);

export const workflowStepSchema = z.object({
  id: z.string().optional(),
  workflowId: z.string().optional(),
  stepNumber: z.coerce.number().min(1),
  stepName: z.string().min(1, 'Step name is required'),
  stepType: z.enum(WORKFLOW_STEP_TYPES),
  department: z.string().default(''),
  assignedRole: z.string().min(1, 'Assigned role is required'),
  assignedUser: z.string().default(''),
  isMandatory: z.boolean().default(true),
  canApprove: z.boolean().default(false),
  canReject: z.boolean().default(false),
  canSendBack: z.boolean().default(false),
  requireESignature: z.boolean().default(false),
  requireComment: z.boolean().default(false),
  dueDays: z.coerce.number().min(0).default(3),
  escalationRole: z.string().default(''),
  conditionExpression: z.string().default(''),
  nextStepOnApprove: z.string().default(''),
  nextStepOnReject: z.string().default(''),
  isParallel: z.boolean().default(false),
  status: z.enum(RECORD_STATUSES).default('Active'),
  isDeleted: z.boolean().optional(),
});

export const workflowSchema = z.object({
  ...baseFields,
  workflowId: z.string().default(''),
  workflowCode: z.string().min(1, 'Workflow code is required'),
  workflowName: z.string().min(1, 'Workflow name is required'),
  moduleName: z.string().min(1, 'Module name is required'),
  subModule: z.string().default(''),
  workflowCategory: z.string().default(''),
  businessUnit: z.string().default(''),
  site: z.string().default(''),
  department: z.string().default(''),
  workflowType: z.enum(WORKFLOW_TYPES).default('Multi Level Approval'),
  triggerEvent: z.string().default(''),
  priority: z.string().default('Medium'),
  slaHours: z.coerce.number().min(0).optional(),
  parallelApproval: z.boolean().default(false),
  sequentialApproval: z.boolean().default(true),
  conditionalRouting: z.boolean().default(false),
  workflowVersion: z.string().default('1.0'),
  effectiveDate: z.string().default(''),
  reviewDate: z.string().default(''),
  expiryDate: z.string().default(''),
  initiatorRole: z.string().default(''),
  reviewerRoles: z.string().default(''),
  approverRoles: z.string().default(''),
  reviewerRole: z.string().default(''),
  approverRole: z.string().default(''),
  finalApproverRole: z.string().default(''),
  escalationRole: z.string().default(''),
  approvalLevels: z.coerce.number().min(1).default(1),
  requireESignature: z.boolean().default(true),
  requireRemarks: z.boolean().default(true),
  allowRejection: z.boolean().default(true),
  allowResubmission: z.boolean().default(true),
  allowDelegation: z.boolean().default(false),
  autoEscalationEnabled: z.boolean().default(false),
  autoEscalationDays: z.coerce.number().min(0).default(3),
  escalationDays: z.coerce.number().min(0).default(3),
  targetCompletionDays: z.coerce.number().min(0).default(30),
  description: z.string().default(''),
  workflowChain: z.string().default(''),
  remarks: z.string().default(''),
  isArchived: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
  deletedAt: z.string().optional(),
  deletedBy: z.string().optional(),
  clonedFrom: z.string().optional(),
});

export const workflowFormSchema = z.object({
  workflowCode: z.string().min(1, 'Workflow code is required'),
  workflowName: z.string().min(1, 'Workflow name is required'),
  moduleName: z.enum(WORKFLOW_MODULE_OPTIONS),
  subModule: z.string().default(''),
  workflowCategory: z.string().default('Approval'),
  businessUnit: z.string().default(''),
  site: z.string().default(''),
  department: z.string().default(''),
  workflowType: z.enum(WORKFLOW_TYPES),
  triggerEvent: z.string().default(''),
  priority: z.string().default('Medium'),
  slaHours: z.coerce.number().min(0).optional(),
  parallelApproval: z.boolean().default(false),
  sequentialApproval: z.boolean().default(true),
  conditionalRouting: z.boolean().default(false),
  workflowVersion: z.string().default('1.0'),
  effectiveDate: z.string().default(''),
  reviewDate: z.string().default(''),
  expiryDate: z.string().default(''),
  initiatorRole: z.string().default(''),
  reviewerRoles: z.string().default(''),
  approverRoles: z.string().default(''),
  finalApproverRole: z.string().default(''),
  escalationRole: z.string().default(''),
  approvalLevels: z.coerce.number().min(1).default(1),
  requireESignature: z.boolean().default(true),
  requireRemarks: z.boolean().default(true),
  allowRejection: z.boolean().default(true),
  allowResubmission: z.boolean().default(true),
  allowDelegation: z.boolean().default(false),
  autoEscalationEnabled: z.boolean().default(false),
  escalationDays: z.coerce.number().min(0).default(3),
  targetCompletionDays: z.coerce.number().min(0).default(30),
  description: z.string().default(''),
  remarks: z.string().default(''),
  changeReason: z.string().trim().max(500).default(''),
  steps: z.array(workflowStepSchema).min(1, 'At least one workflow step is required'),
}).refine(
  (data) => !APPROVAL_WORKFLOW_TYPES.includes(data.workflowType as typeof APPROVAL_WORKFLOW_TYPES[number])
    || data.finalApproverRole.trim().length > 0
    || data.steps.some((s) => s.stepType === 'Final Approve' || s.stepType === 'Approve' || s.stepType === 'End'),
  { message: 'Final approver is required for approval workflows', path: ['finalApproverRole'] },
).refine(
  (data) => {
    const names = data.steps.map((s) => s.stepName.trim().toLowerCase());
    return new Set(names).size === names.length;
  },
  { message: 'Duplicate step names are not allowed (prevents circular routing)', path: ['steps'] },
);

export const approvalMatrixSchema = z.object({
  ...baseFields,
  approvalMatrixId: z.string().default(''),
  matrixId: z.string().default(''),
  matrixCode: z.string().min(1, 'Matrix code is required'),
  matrixName: z.string().min(1, 'Matrix name is required'),
  description: z.string().default(''),
  moduleName: z.string().min(1, 'Module is required'),
  module: z.string().default(''),
  subModule: z.string().default(''),
  department: z.string().min(1, 'Department is required'),
  siteLocation: z.string().default(''),
  businessUnit: z.string().default(''),
  workflowCode: z.string().default(''),
  documentType: z.string().default(''),
  category: z.string().default(''),
  priority: z.string().default('Medium'),
  productOptional: z.string().default(''),
  processOptional: z.string().default(''),
  riskLevel: z.enum(RISK_LEVELS).default('Medium'),
  approvalMode: z.string().default('Sequential'),
  matrixVersion: z.string().default('1.0'),
  effectiveDate: z.string().default(''),
  reviewDate: z.string().default(''),
  preparedByRole: z.string().default(''),
  reviewedByRole: z.string().default(''),
  verifiedByRole: z.string().default(''),
  approvedByRole: z.string().default(''),
  finalApproverRole: z.string().default(''),
  escalationRole: z.string().default(''),
  level1Reviewer: z.string().default(''),
  level2Reviewer: z.string().default(''),
  finalApprover: z.string().default(''),
  approvalGroup: z.string().default(''),
  quorumCount: z.coerce.number().min(0).optional(),
  minimumApprovalLevel: z.coerce.number().min(1).default(1),
  slaHours: z.coerce.number().min(0).optional(),
  reminderHours: z.coerce.number().min(0).optional(),
  autoEscalationEnabled: z.boolean().default(false),
  autoEscalationHours: z.coerce.number().min(0).optional(),
  autoApproveEnabled: z.boolean().default(false),
  allowReject: z.boolean().default(true),
  allowReturn: z.boolean().default(true),
  allowRework: z.boolean().default(true),
  allowResubmit: z.boolean().default(true),
  allowCancel: z.boolean().default(false),
  allowSkip: z.boolean().default(false),
  eSignatureRequired: z.boolean().default(true),
  eSignRequired: z.boolean().default(true),
  digitalSignatureRequired: z.boolean().default(false),
  approvalCommentRequired: z.boolean().default(true),
  mandatoryRemarks: z.boolean().default(true),
  parallelApprovalAllowed: z.boolean().default(false),
  sequentialApprovalRequired: z.boolean().default(true),
  conditionalApprovalEnabled: z.boolean().default(false),
  conditionExpression: z.string().default(''),
  delegationAllowed: z.boolean().default(false),
  remarks: z.string().default(''),
  isArchived: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
  deletedAt: z.string().optional(),
  deletedBy: z.string().optional(),
  clonedFrom: z.string().optional(),
});

export const approvalMatrixFormSchema = z.object({
  matrixCode: z.string().min(1, 'Matrix code is required'),
  matrixName: z.string().min(1, 'Matrix name is required'),
  description: z.string().default(''),
  moduleName: z.enum(APPROVAL_MATRIX_MODULES),
  subModule: z.string().default(''),
  department: z.string().min(1, 'Department is required'),
  siteLocation: z.string().default(''),
  businessUnit: z.string().default(''),
  workflowCode: z.string().default(''),
  documentType: z.string().default(''),
  category: z.string().default(''),
  priority: z.string().default('Medium'),
  productOptional: z.string().default(''),
  processOptional: z.string().default(''),
  riskLevel: z.enum(RISK_LEVELS).default('Medium'),
  approvalMode: z.enum(APPROVAL_MODES).default('Sequential'),
  matrixVersion: z.string().default('1.0'),
  effectiveDate: z.string().default(''),
  reviewDate: z.string().default(''),
  preparedByRole: z.string().default(''),
  reviewedByRole: z.string().default(''),
  verifiedByRole: z.string().default(''),
  approvedByRole: z.string().default(''),
  finalApproverRole: z.string().default(''),
  escalationRole: z.string().default(''),
  approvalGroup: z.string().default(''),
  quorumCount: z.coerce.number().min(0).optional(),
  minimumApprovalLevel: z.coerce.number().min(1).default(1),
  slaHours: z.coerce.number().min(0).optional(),
  reminderHours: z.coerce.number().min(0).optional(),
  autoEscalationEnabled: z.boolean().default(false),
  autoEscalationHours: z.coerce.number().min(0).optional(),
  autoApproveEnabled: z.boolean().default(false),
  allowReject: z.boolean().default(true),
  allowReturn: z.boolean().default(true),
  allowRework: z.boolean().default(true),
  allowResubmit: z.boolean().default(true),
  allowCancel: z.boolean().default(false),
  allowSkip: z.boolean().default(false),
  eSignatureRequired: z.boolean().default(true),
  digitalSignatureRequired: z.boolean().default(false),
  approvalCommentRequired: z.boolean().default(true),
  parallelApprovalAllowed: z.boolean().default(false),
  sequentialApprovalRequired: z.boolean().default(true),
  conditionalApprovalEnabled: z.boolean().default(false),
  conditionExpression: z.string().default(''),
  delegationAllowed: z.boolean().default(false),
  remarks: z.string().default(''),
  changeReason: z.string().trim().max(500).default(''),
}).refine(
  (data) => {
    const hasApprover = data.finalApproverRole.trim() || data.approvedByRole.trim()
      || data.reviewedByRole.trim() || data.verifiedByRole.trim();
    return Boolean(hasApprover);
  },
  { message: 'At least one approver role is required', path: ['finalApproverRole'] },
).refine(
  (data) => data.riskLevel !== 'High' && data.riskLevel !== 'Critical'
    || data.finalApproverRole.trim().length > 0,
  { message: 'Final approver is required for High and Critical risk', path: ['finalApproverRole'] },
).refine(
  (data) => data.riskLevel !== 'Critical' || data.finalApproverRole === 'head_qa',
  { message: 'Critical risk requires Head QA as final approver', path: ['finalApproverRole'] },
).refine(
  (data) => {
    const roles = [
      data.preparedByRole, data.reviewedByRole, data.verifiedByRole,
      data.approvedByRole, data.finalApproverRole,
    ].map((r) => r.trim().toLowerCase()).filter(Boolean);
    // Detect exact full-chain duplicates that create circular loops of same role
    if (roles.length >= 3 && new Set(roles).size === 1) return false;
    return true;
  },
  { message: 'Circular approval chain detected — all levels use the same role', path: ['finalApproverRole'] },
).refine(
  (data) => data.approvalMode !== 'Quorum' || (data.quorumCount != null && data.quorumCount > 0),
  { message: 'Quorum count is required for Quorum approval mode', path: ['quorumCount'] },
);

export const documentNumberingSchema = z.object({
  ...baseFields,
  numberingId: z.string().default(''),
  numberingCode: z.string().min(1, 'Numbering code is required'),
  numberingName: z.string().default(''),
  description: z.string().default(''),
  moduleName: z.string().min(1, 'Module is required'),
  module: z.string().default(''),
  documentType: z.string().min(1, 'Document type is required'),
  documentCategory: z.string().default(''),
  department: z.string().default(''),
  site: z.string().default(''),
  businessUnit: z.string().default(''),
  company: z.string().default(''),
  location: z.string().default(''),
  product: z.string().default(''),
  workflowCode: z.string().default(''),
  prefix: z.string().min(1, 'Prefix is required'),
  suffix: z.string().default(''),
  siteCode: z.string().default(''),
  departmentCode: z.string().default(''),
  productCodeOptional: z.string().default(''),
  yearFormat: z.enum(NUMBERING_YEAR_FORMATS).default('YYYY'),
  monthFormat: z.enum(NUMBERING_MONTH_FORMATS).default('None'),
  separator: z.enum(NUMBERING_SEPARATOR_OPTIONS).default('/'),
  runningNumberLength: z.coerce.number().min(1).default(4),
  runningNumber: z.coerce.number().min(1).default(4),
  startingNumber: z.coerce.number().min(0).default(0),
  currentRunningNumber: z.coerce.number().min(0).default(0),
  currentNumber: z.coerce.number().min(0).default(0),
  resetFrequency: z.enum(NUMBERING_RESET_FREQUENCIES).default('Yearly'),
  revisionFormat: z.enum(REVISION_FORMAT_OPTIONS).default('00'),
  formatTokens: z.string().default('PREFIX,DEPARTMENT_CODE,RUNNING_NUMBER,YEAR'),
  exampleNumberPreview: z.string().default(''),
  exampleFormat: z.string().default(''),
  numberingVersion: z.string().default('1.0'),
  effectiveDate: z.string().default(''),
  reviewDate: z.string().default(''),
  autoGenerateEnabled: z.boolean().default(true),
  manualOverrideAllowed: z.boolean().default(false),
  allowSkipSequence: z.boolean().default(false),
  remarks: z.string().default(''),
  isArchived: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
  deletedAt: z.string().optional(),
  deletedBy: z.string().optional(),
  clonedFrom: z.string().optional(),
});

export const documentNumberingFormSchema = z.object({
  numberingCode: z.string().min(1, 'Numbering code is required'),
  numberingName: z.string().default(''),
  description: z.string().default(''),
  moduleName: z.enum(DOCUMENT_NUMBERING_MODULES),
  documentType: z.string().min(1, 'Document type is required'),
  documentCategory: z.string().default(''),
  department: z.string().default(''),
  site: z.string().default(''),
  businessUnit: z.string().default(''),
  company: z.string().default(''),
  location: z.string().default(''),
  product: z.string().default(''),
  workflowCode: z.string().default(''),
  prefix: z.string().min(1, 'Prefix is required'),
  suffix: z.string().default(''),
  siteCode: z.string().default(''),
  departmentCode: z.string().default(''),
  productCodeOptional: z.string().default(''),
  yearFormat: z.enum(NUMBERING_YEAR_FORMATS).default('YYYY'),
  monthFormat: z.enum(NUMBERING_MONTH_FORMATS).default('None'),
  separator: z.enum(NUMBERING_SEPARATOR_OPTIONS).default('/'),
  runningNumberLength: z.coerce.number().min(1, 'Running number length is required'),
  startingNumber: z.coerce.number().min(0).default(0),
  currentRunningNumber: z.coerce.number().min(0, 'Current running number is required'),
  resetFrequency: z.enum(NUMBERING_RESET_FREQUENCIES).default('Yearly'),
  revisionFormat: z.enum(REVISION_FORMAT_OPTIONS).default('00'),
  formatTokens: z.string().min(1, 'Format tokens are required'),
  numberingVersion: z.string().default('1.0'),
  effectiveDate: z.string().default(''),
  reviewDate: z.string().default(''),
  autoGenerateEnabled: z.boolean().default(true),
  manualOverrideAllowed: z.boolean().default(false),
  allowSkipSequence: z.boolean().default(false),
  remarks: z.string().default(''),
  changeReason: z.string().trim().max(500).default(''),
}).refine(
  (data) => data.resetFrequency !== 'Yearly' || data.formatTokens.includes('YEAR') || data.yearFormat === 'None',
  { message: 'Yearly reset should include YEAR token in format', path: ['formatTokens'] },
).refine(
  (data) => data.resetFrequency !== 'Monthly' || data.formatTokens.includes('MONTH') || data.monthFormat === 'None',
  { message: 'Monthly reset should include MONTH token in format', path: ['formatTokens'] },
);

export const auditLogSchema = z.object({
  id: z.string().optional(),
  dateTime: z.string(),
  userId: z.string().default(''),
  userName: z.string().default(''),
  module: z.string().default(''),
  recordId: z.string().default(''),
  action: z.string().default(''),
  oldValue: z.string().default(''),
  newValue: z.string().default(''),
  reason: z.string().default(''),
  ipAddress: z.string().default(''),
  device: z.string().default(''),
  status: z.string().default('Success'),
});

export const auditTrailEntrySchema = z.object({
  id: z.string().optional(),
  auditId: z.string().default(''),
  transactionId: z.string().default(''),
  referenceId: z.string().default(''),
  dateTime: z.string(),
  timestamp: z.string().optional(),
  timezone: z.string().default('UTC'),
  moduleName: z.string().min(1),
  subModule: z.string().default(''),
  screen: z.string().default(''),
  collectionName: z.string().default(''),
  recordId: z.string().default(''),
  documentId: z.string().optional(),
  documentNumber: z.string().default(''),
  actionType: z.string().min(1),
  action: z.string().optional(),
  actionDescription: z.string().default(''),
  fieldName: z.string().default(''),
  oldValue: z.union([z.string(), z.record(z.unknown())]).optional(),
  newValue: z.union([z.string(), z.record(z.unknown())]).optional(),
  changedFields: z.string().default(''),
  changedByUserId: z.string().default(''),
  changedByUserName: z.string().default(''),
  changedByRole: z.string().default(''),
  userId: z.string().optional(),
  userName: z.string().optional(),
  employeeId: z.string().default(''),
  username: z.string().default(''),
  fullName: z.string().default(''),
  role: z.string().default(''),
  department: z.string().default(''),
  site: z.string().default(''),
  businessUnit: z.string().default(''),
  company: z.string().default(''),
  reasonForChange: z.string().default(''),
  reason: z.string().optional(),
  remarks: z.string().default(''),
  ipAddress: z.string().default(''),
  deviceInfo: z.string().default(''),
  device: z.string().optional(),
  browserInfo: z.string().default(''),
  operatingSystem: z.string().default(''),
  sessionId: z.string().default(''),
  requestId: z.string().default(''),
  workflowId: z.string().default(''),
  approvalLevel: z.string().default(''),
  location: z.string().default(''),
  eSignatureRequired: z.boolean().default(false),
  eSignatureStatus: z.string().default(''),
  eSignatureId: z.string().default(''),
  previousHash: z.string().default(''),
  integrityHash: z.string().default(''),
  status: z.enum(AUDIT_LOG_STATUSES).default('Success'),
  isArchived: z.boolean().optional(),
  copiedToArchive: z.boolean().optional(),
});

export const esignSettingsSchema = z.object({
  ...baseFields,
  esignSettingId: z.string().default(''),
  settingCode: z.string().min(1, 'Setting code is required'),
  moduleName: z.string().min(1, 'Module is required'),
  actionType: z.string().min(1, 'Action type is required'),
  moduleAliases: z.array(z.string()).default([]),
  actionAliases: z.array(z.string()).default([]),
  signatureMeaning: z.string().min(1, 'Signature meaning is required'),
  allowedMeanings: z.array(z.string()).default([]),
  requirePasswordReAuthentication: z.boolean().default(true),
  requirePasswordConfirmation: z.boolean().default(true),
  requireCommentReason: z.boolean().default(true),
  requireReason: z.boolean().default(true),
  requireRoleVerification: z.boolean().default(true),
  requireDepartmentVerification: z.boolean().default(false),
  requireActiveSession: z.boolean().default(true),
  sessionTimeoutMinutes: z.coerce.number().min(1).default(15),
  sessionTimeout: z.coerce.number().min(1).default(15),
  maxFailedEsignAttempts: z.coerce.number().min(1).default(3),
  lockAccountAfterFailedAttempts: z.boolean().default(true),
  allowDelegatedSignature: z.boolean().default(false),
  requireFinalApprovalSignature: z.boolean().default(false),
  showSignatureStatement: z.boolean().default(true),
  signatureStatementText: z.string().default(''),
  signatureMeanings: z.array(z.enum(SIGNATURE_MEANINGS)).default([...SIGNATURE_MEANINGS]),
  authenticationMethods: z.array(z.string()).default(['Password Confirmation']),
  allowedRoles: z.array(z.string()).default([]),
  allowedDepartments: z.array(z.string()).default([]),
  siteScope: z.string().default(''),
  businessUnitScope: z.string().default(''),
  remarks: z.string().default(''),
  isDeleted: z.boolean().optional(),
  changeReason: z.string().optional(),
});

export const esignSettingFormSchema = z.object({
  settingCode: z.string().min(1, 'Setting code is required'),
  moduleName: z.string().min(1, 'Module is required'),
  actionType: z.string().min(1, 'Action type is required'),
  moduleAliases: z.string().default(''),
  actionAliases: z.string().default(''),
  signatureMeaning: z.string().min(1, 'Signature meaning is required'),
  requirePasswordReAuthentication: z.boolean().default(true),
  requireCommentReason: z.boolean().default(true),
  requireRoleVerification: z.boolean().default(true),
  requireDepartmentVerification: z.boolean().default(false),
  requireActiveSession: z.boolean().default(true),
  sessionTimeoutMinutes: z.coerce.number().min(1).default(15),
  maxFailedEsignAttempts: z.coerce.number().min(1).default(3),
  lockAccountAfterFailedAttempts: z.boolean().default(true),
  allowDelegatedSignature: z.boolean().default(false),
  requireFinalApprovalSignature: z.boolean().default(false),
  showSignatureStatement: z.boolean().default(true),
  signatureStatementText: z.string().default(''),
  allowedRoles: z.string().default(''),
  allowedDepartments: z.string().default(''),
  remarks: z.string().default(''),
  changeReason: z.string().min(5, 'Change reason is required (min 5 characters)'),
});

export const esignRecordSchema = z.object({
  id: z.string().optional(),
  esignRecordId: z.string().default(''),
  transactionId: z.string().default(''),
  referenceId: z.string().default(''),
  workflowId: z.string().default(''),
  approvalLevel: z.string().default(''),
  moduleName: z.string().default(''),
  subModule: z.string().default(''),
  documentNumber: z.string().default(''),
  recordId: z.string().default(''),
  actionType: z.string().default(''),
  signatureMeaning: z.string().default(''),
  reason: z.string().default(''),
  reasonComment: z.string().default(''),
  comments: z.string().default(''),
  userId: z.string().default(''),
  employeeId: z.string().default(''),
  username: z.string().default(''),
  userName: z.string().default(''),
  userEmail: z.string().default(''),
  userRole: z.string().default(''),
  department: z.string().default(''),
  company: z.string().default(''),
  businessUnit: z.string().default(''),
  site: z.string().default(''),
  signedDateTime: z.string().default(''),
  timestampUtc: z.string().default(''),
  timezone: z.string().default(''),
  ipAddress: z.string().default(''),
  deviceInfo: z.string().default(''),
  browser: z.string().default(''),
  operatingSystem: z.string().default(''),
  authenticationMethod: z.string().default('Password Confirmation'),
  mfaStatus: z.string().default('Not Applicable'),
  digitalHash: z.string().default(''),
  authenticationStatus: z.string().default('Success'),
  status: z.string().default('Signed'),
  isTest: z.boolean().default(false),
  settingId: z.string().default(''),
  settingCode: z.string().default(''),
  immutable: z.boolean().optional(),
});

export const notificationSettingSchema = z.object({
  ...baseFields,
  notificationSettingId: z.string().default(''),
  notificationCode: z.string().min(1, 'Notification code is required'),
  eventName: z.string().min(1, 'Event name is required'),
  moduleName: z.string().min(1, 'Module is required'),
  eventTrigger: z.string().min(1, 'Event trigger is required'),
  notificationType: z.enum(NOTIFICATION_CHANNEL_TYPES).default('In-App + Email'),
  recipientRole: z.string().default(''),
  recipientUserOptional: z.string().default(''),
  recipientDepartmentOptional: z.string().default(''),
  ccRoleOptional: z.string().default(''),
  escalationRole: z.string().default(''),
  notifyBeforeDueDays: z.coerce.number().min(0).default(3),
  beforeDueDays: z.coerce.number().min(0).default(3),
  escalationAfterDays: z.coerce.number().min(0).default(7),
  escalationDays: z.coerce.number().min(0).default(7),
  repeatReminder: z.boolean().default(false),
  reminderFrequency: z.enum(REMINDER_FREQUENCIES).default('None'),
  templateSubject: z.string().default(''),
  templateBody: z.string().default(''),
  template: z.string().default(''),
  priority: z.enum(NOTIFICATION_PRIORITIES).default('Medium'),
  enableInAppNotification: z.boolean().default(true),
  inAppEnabled: z.boolean().default(true),
  enableEmailNotification: z.boolean().default(true),
  emailEnabled: z.boolean().default(true),
  enableSmsNotification: z.boolean().default(false),
  smsEnabled: z.boolean().default(false),
  remarks: z.string().default(''),
  isDeleted: z.boolean().optional(),
  eventAliases: z.array(z.string()).default([]),
  preventDuplicates: z.boolean().default(true),
  duplicateWindowMinutes: z.coerce.number().min(1).default(60),
  enablePushNotification: z.boolean().default(false),
  enableWebhook: z.boolean().default(false),
  webhookUrl: z.string().default(''),
  changeReason: z.string().optional(),
});

export const notificationSettingFormSchema = z.object({
  notificationCode: z.string().min(1, 'Notification code is required'),
  eventName: z.string().min(1, 'Event name is required'),
  moduleName: z.string().min(1, 'Module is required'),
  eventTrigger: z.string().min(1, 'Event trigger is required'),
  eventAliases: z.string().default(''),
  notificationType: z.enum(NOTIFICATION_CHANNEL_TYPES).default('In-App + Email'),
  recipientRole: z.string().default(''),
  recipientUserOptional: z.string().default(''),
  recipientDepartmentOptional: z.string().default(''),
  ccRoleOptional: z.string().default(''),
  escalationRole: z.string().default(''),
  notifyBeforeDueDays: z.coerce.number().min(0).default(3),
  escalationAfterDays: z.coerce.number().min(0).default(7),
  repeatReminder: z.boolean().default(false),
  reminderFrequency: z.enum(REMINDER_FREQUENCIES).default('None'),
  templateSubject: z.string().default(''),
  templateBody: z.string().min(1, 'Template body is required'),
  priority: z.enum(NOTIFICATION_PRIORITIES).default('Medium'),
  enableInAppNotification: z.boolean().default(true),
  enableEmailNotification: z.boolean().default(true),
  enableSmsNotification: z.boolean().default(false),
  remarks: z.string().default(''),
  changeReason: z.string().min(5, 'Change reason is required (min 5 characters)'),
}).refine(
  (data) => data.recipientRole.trim() || data.recipientUserOptional.trim(),
  { message: 'Recipient role or user is required', path: ['recipientRole'] },
).refine(
  (data) => !data.enableEmailNotification || data.templateSubject.trim().length > 0,
  { message: 'Template subject is required for email notifications', path: ['templateSubject'] },
);

export const backupHistorySchema = z.object({
  ...baseFields,
  backupId: z.string().min(1),
  backupNumber: z.string().min(1, 'Backup number is required'),
  backupType: z.enum(BACKUP_TYPES),
  backupScope: z.enum(BACKUP_SCOPES),
  backupDateTime: z.string(),
  backupDate: z.string().optional(), // legacy
  backupStatus: z.enum(BACKUP_STATUSES).default('Pending'),
  fileName: z.string().default(''),
  fileSize: z.string().default(''),
  fileSizeBytes: z.coerce.number().min(0).default(0),
  storageLocation: z.string().default(''),
  filePath: z.string().default(''), // legacy
  collectionsIncluded: z.array(z.string()).default([]),
  recordsCount: z.coerce.number().min(0).default(0),
  backupFrequency: z.enum(BACKUP_FREQUENCIES).default('Manual Only'),
  nextBackupDue: z.string().default(''),
  restorePointCreated: z.boolean().default(false),
  checksum: z.string().default(''),
  integrityStatus: z.string().default('Pending'),
  encryptionStatus: z.string().default(''),
  encryptionAlgorithm: z.string().default('AES-256-GCM'),
  storageProvider: z.string().default('Firebase Cloud Storage'),
  compressionRatio: z.string().default('1.0'),
  version: z.string().default('1'),
  retentionPolicyDays: z.coerce.number().min(0).default(90),
  expirationDate: z.string().default(''),
  isProtected: z.boolean().default(false),
  failureReason: z.string().default(''),
  durationMs: z.coerce.number().min(0).default(0),
  changeReason: z.string().default(''),
  remarks: z.string().default(''),
  isArchived: z.boolean().default(false),
  archivedAt: z.string().default(''),
  archivedBy: z.string().default(''),
  isDeleted: z.boolean().optional(),
});

export const backupFormSchema = z.object({
  backupNumber: z.string().min(1, 'Backup number is required'),
  backupType: z.enum(BACKUP_TYPES),
  backupScope: z.enum(BACKUP_SCOPES),
  selectedCollections: z.array(z.string()).default([]),
  backupFrequency: z.enum(BACKUP_FREQUENCIES).default('Manual Only'),
  remarks: z.string().default(''),
  changeReason: z.string().min(5, 'Change reason is required (min 5 characters)'),
  isProtected: z.boolean().default(false),
}).refine(
  (data) => data.backupScope !== 'Selected Collections' || data.selectedCollections.length > 0,
  { message: 'Select at least one collection', path: ['selectedCollections'] },
);

export const backupSettingsSchema = z.object({
  ...baseFields,
  autoBackupEnabled: z.boolean().default(false),
  backupFrequency: z.enum(BACKUP_FREQUENCIES).default('Weekly'),
  backupTime: z.string().default('02:00'),
  backupScope: z.enum(BACKUP_SCOPES).default('Full System'),
  retentionPeriodDays: z.coerce.number().min(1, 'Retention period must be numeric').default(90),
  notifyAdminOnSuccess: z.boolean().default(true),
  notifyAdminOnFailure: z.boolean().default(true),
  lastBackupDate: z.string().default(''),
  nextBackupDate: z.string().default(''),
  changeReason: z.string().default(''),
}).refine(
  (data) => !data.autoBackupEnabled || data.backupFrequency !== 'Manual Only',
  { message: 'Backup frequency is required when auto backup is enabled', path: ['backupFrequency'] },
);

export const restoreHistorySchema = z.object({
  ...baseFields,
  restoreId: z.string().min(1),
  backupId: z.string().min(1),
  restoreDateTime: z.string(),
  restoreType: z.enum(RESTORE_TYPES),
  restoredBy: z.string().default(''),
  restoreStatus: z.enum(RESTORE_STATUSES).default('Requested'),
  collectionsRestored: z.array(z.string()).default([]),
  recordsRestored: z.coerce.number().min(0).default(0),
  reasonForRestore: z.string().min(1, 'Reason for restore is required'),
  approvalRequired: z.boolean().default(true),
  approvedBy: z.string().default(''),
  approvedAt: z.string().default(''),
  preRestoreBackupId: z.string().default(''),
  dryRun: z.boolean().default(false),
  esignRecordId: z.string().default(''),
  remarks: z.string().default(''),
  isArchived: z.boolean().default(false),
  failureReason: z.string().default(''),
  durationMs: z.coerce.number().min(0).default(0),
});

export const restoreRequestFormSchema = z.object({
  backupId: z.string().min(1, 'Backup is required'),
  restoreType: z.enum(RESTORE_TYPES),
  selectedCollections: z.array(z.string()).default([]),
  reasonForRestore: z.string().min(5, 'Reason for restore is required (min 5 characters)'),
  remarks: z.string().default(''),
  dryRun: z.boolean().default(false),
  esignRecordId: z.string().default(''),
}).refine(
  (data) => data.restoreType !== 'Selected Collection Restore' || data.selectedCollections.length > 0,
  { message: 'Select at least one collection to restore', path: ['selectedCollections'] },
);

export const systemSettingsSchema = z.object({
  ...baseFields,
  // General / Organization
  applicationName: z.string().min(1, 'Application name is required'),
  applicationShortName: z.string().default('PharmaQMS'),
  companyName: z.string().default(''),
  businessUnit: z.string().default(''),
  companyDefaultSite: z.string().default(''),
  defaultLanguage: z.string().default('en'),
  timezone: z.string().min(1, 'Timezone is required'),
  dateFormat: z.enum(DATE_FORMATS),
  timeFormat: z.enum(TIME_FORMATS),
  defaultCurrency: z.enum(CURRENCY_OPTIONS).default('INR'),
  numberFormat: z.string().default('en-IN'),
  financialYearStartMonth: z.enum(FINANCIAL_YEAR_MONTHS).default('April'),
  supportEmail: z.string().default(''),
  supportPhone: z.string().default(''),
  applicationVersion: z.string().default('1.0.0'),
  environment: z.enum(SYSTEM_ENVIRONMENTS).default('Production'),
  defaultDashboard: z.string().default('/admin'),
  landingPage: z.string().default('/dashboard'),
  faviconUrl: z.string().default(''),
  secondaryColor: z.string().default('#0f172a'),
  // Security
  enableRoleBasedAccess: z.boolean().default(true),
  enablePermissionGuard: z.boolean().default(true),
  enableAuditTrail: z.boolean().default(true),
  enableESignature: z.boolean().default(true),
  enableTwoFactorAuth: z.boolean().default(false),
  allowMultipleSessions: z.boolean().default(true),
  allowIpRestriction: z.boolean().default(false),
  allowedIpList: z.string().default(''),
  enableAccountLockout: z.boolean().default(true),
  maxFailedLoginAttempts: z.coerce.number().min(1).default(5),
  accountLockDurationMinutes: z.coerce.number().min(1).default(30),
  enableGoogleLogin: z.boolean().default(false),
  enableMicrosoftLogin: z.boolean().default(false),
  ssoReady: z.boolean().default(false),
  ldapReady: z.boolean().default(false),
  oauthReady: z.boolean().default(false),
  // Password policy (embedded)
  minPasswordLength: z.coerce.number().min(6).default(8),
  requireUppercase: z.boolean().default(true),
  requireLowercase: z.boolean().default(true),
  requireNumber: z.boolean().default(true),
  requireSpecialChar: z.boolean().default(true),
  passwordExpiryDays: z.coerce.number().min(0).default(90),
  preventLastPasswordReuseCount: z.coerce.number().min(0).default(5),
  forcePasswordChangeOnFirstLogin: z.boolean().default(true),
  // Session
  sessionTimeoutMinutes: z.coerce.number().min(5).default(30),
  idleTimeoutMinutes: z.coerce.number().min(5).default(15),
  rememberMeEnabled: z.boolean().default(true),
  autoLogoutWarningMinutes: z.coerce.number().min(1).default(2),
  // File upload / storage
  allowedFileTypes: z.string().default('.pdf,.doc,.docx,.xls,.xlsx,.jpg,.png'),
  maxFileSizeMb: z.coerce.number().min(1).default(10),
  enableVirusScanPlaceholder: z.boolean().default(false),
  storagePathFormat: z.string().default('{module}/{year}/{recordId}'),
  allowPdf: z.boolean().default(true),
  allowExcel: z.boolean().default(true),
  allowWord: z.boolean().default(true),
  allowImages: z.boolean().default(true),
  // Theme / branding
  defaultTheme: z.enum(['light', 'dark', 'system']).default('light'),
  enableDarkMode: z.boolean().default(true),
  primaryColor: z.string().default('#2563eb'),
  sidebarMode: z.enum(SIDEBAR_MODES).default('Expanded'),
  logoDisplayMode: z.enum(LOGO_DISPLAY_MODES).default('Full Logo'),
  compactMode: z.boolean().default(false),
  companyLogo: z.string().default(''),
  // Maintenance
  maintenanceModeEnabled: z.boolean().default(false),
  maintenanceMessage: z.string().default('System is under scheduled maintenance. Please try again later.'),
  allowedAdminAccessDuringMaintenance: z.boolean().default(true),
  scheduledMaintenanceStart: z.string().default(''),
  scheduledMaintenanceEnd: z.string().default(''),
  // System logs / performance
  enableSystemLogs: z.boolean().default(true),
  logRetentionDays: z.coerce.number().min(1).default(90),
  enableErrorTracking: z.boolean().default(true),
  enablePerformanceLogs: z.boolean().default(false),
  enableCaching: z.boolean().default(true),
  cacheTtlSeconds: z.coerce.number().min(10).default(120),
  // Compliance
  enableFda21CfrPart11: z.boolean().default(true),
  enableEuGmpAnnex11: z.boolean().default(true),
  enableAlcoaPlus: z.boolean().default(true),
  enableWhoGmp: z.boolean().default(true),
  enablePicsGmp: z.boolean().default(true),
  enableIchQ10: z.boolean().default(true),
  enableIso27001: z.boolean().default(true),
  enableGamp5: z.boolean().default(true),
  enableDocumentVersioning: z.boolean().default(true),
  enableApprovalWorkflow: z.boolean().default(true),
  recordRetentionDays: z.coerce.number().min(30).default(2555),
  // Feature flags (global; module-level flags live in Module Configuration)
  enableBetaFeatures: z.boolean().default(false),
  enableExperimentalFeatures: z.boolean().default(false),
  // API / integrations (flags only — secrets stay in env)
  enableRestApi: z.boolean().default(false),
  enableWebhooks: z.boolean().default(false),
  smtpConfigured: z.boolean().default(false),
  smsGatewayConfigured: z.boolean().default(false),
  // Versioning metadata
  configVersion: z.coerce.number().min(1).default(1),
  publishedVersion: z.coerce.number().optional(),
  configurationStatus: z.enum(['Draft', 'Published', 'Archived']).default('Published'),
  draftMode: z.boolean().default(false),
  // Legacy compatibility
  passwordPolicy: z.string().default(''),
  sessionTimeout: z.coerce.number().optional(),
  maxLoginAttempts: z.coerce.number().optional(),
  accountLockDuration: z.coerce.number().optional(),
  maxUploadSize: z.coerce.number().optional(),
  maintenanceMode: z.boolean().optional(),
}).refine(
  (data) => !data.maintenanceModeEnabled || data.maintenanceMessage.trim().length > 0,
  { message: 'Maintenance message is required when maintenance mode is enabled', path: ['maintenanceMessage'] },
);

export const loginActivitySchema = z.object({
  ...baseFields,
  status: z.enum(['Active', 'Inactive', 'Closed']).default('Active'),
  loginId: z.string().default(''),
  sessionId: z.string().default(''),
  userId: z.string().default(''),
  employeeId: z.string().default(''),
  username: z.string().default(''),
  userName: z.string().default(''),
  fullName: z.string().default(''),
  email: z.string().default(''),
  role: z.string().default(''),
  department: z.string().default(''),
  businessUnit: z.string().default(''),
  company: z.string().default(''),
  site: z.string().default(''),
  deviceName: z.string().default(''),
  deviceType: z.string().default(''),
  deviceInfo: z.string().default(''),
  deviceFingerprint: z.string().default(''),
  browser: z.string().default(''),
  browserVersion: z.string().default(''),
  operatingSystem: z.string().default(''),
  ipAddress: z.string().default(''),
  macAddress: z.string().default(''),
  geoLocation: z.string().default(''),
  loginTime: z.string().default(''),
  logoutTime: z.string().nullable().default(null),
  sessionDurationMinutes: z.coerce.number().nullable().optional(),
  loginStatus: z.enum(LOGIN_STATUSES).default('Success'),
  eventType: z.string().default(''),
  failureReason: z.string().default(''),
  authenticationMethod: z.string().default('Password'),
  mfaStatus: z.string().default('Not Applicable'),
  rememberMe: z.boolean().default(false),
  riskLevel: z.string().default('Info'),
  sessionTimeoutMinutes: z.coerce.number().optional(),
  idleTimeoutMinutes: z.coerce.number().optional(),
  terminatedBy: z.string().optional(),
  isArchived: z.boolean().optional(),
  immutable: z.boolean().optional(),
});

export const accessReviewSchema = z.object({
  ...baseFields,
  status: z.enum(['Active', 'Inactive', 'Closed']).default('Active'),
  reviewId: z.string().min(1, 'Review ID is required'),
  reviewNumber: z.string().default(''),
  userId: z.string().min(1, 'User ID is required'),
  employeeId: z.string().default(''),
  username: z.string().default(''),
  userName: z.string().min(1, 'Employee name is required'),
  employeeName: z.string().default(''),
  email: z.string().default(''),
  department: z.string().default(''),
  designation: z.string().default(''),
  role: z.string().default(''),
  businessUnit: z.string().default(''),
  company: z.string().default(''),
  site: z.string().default(''),
  manager: z.string().default(''),
  managerId: z.string().default(''),
  reviewerUserId: z.string().default(''),
  reviewerName: z.string().default(''),
  reviewerRole: z.string().default(''),
  reviewPeriod: z.string().min(1, 'Review period is required'),
  reviewStatus: z.enum(ACCESS_REVIEW_STATUSES).default('Pending'),
  riskLevel: z.string().default('Low'),
  accountStatus: z.string().default(''),
  accessStatus: z.string().default(''),
  employmentType: z.string().default(''),
  findings: z.string().default(''),
  actionTaken: z.string().default(''),
  reviewComments: z.string().default(''),
  recommendation: z.string().default(''),
  finalDecision: z.string().default(''),
  reviewDate: z.string().default(''),
  dueDate: z.string().default(''),
  completionDate: z.string().nullable().default(null),
  nextReviewDate: z.string().default(''),
  temporaryAccess: z.boolean().default(false),
  privileged: z.boolean().default(false),
  criticalIssueCount: z.coerce.number().default(0),
  issues: z.array(z.object({
    code: z.string(),
    severity: z.string(),
    message: z.string(),
    resolved: z.boolean().optional(),
  })).optional(),
  electronicSignature: z.record(z.string(), z.unknown()).nullable().optional(),
  signedAt: z.string().nullable().optional(),
  signedBy: z.string().nullable().optional(),
  signatureMeaning: z.string().optional(),
  workflowStage: z.string().default(''),
  immutable: z.boolean().optional(),
  isArchived: z.boolean().optional(),
  changeReason: z.string().optional(),
});

export const passwordPolicySchema = z.object({
  ...baseFields,
  minLength: z.coerce.number().min(6).default(8),
  requireUppercase: z.boolean().default(true),
  requireLowercase: z.boolean().default(true),
  requireNumber: z.boolean().default(true),
  requireSpecialChar: z.boolean().default(true),
  passwordExpiryDays: z.coerce.number().min(0).default(90),
  maxLoginAttempts: z.coerce.number().min(1).default(5),
  lockoutDurationMinutes: z.coerce.number().min(1).default(30),
  preventReuseCount: z.coerce.number().min(0).default(5),
  forceResetOnFirstLogin: z.boolean().default(true),
});

export const moduleConfigSchema = z.object({
  ...baseFields,
  moduleConfigId: z.string().default(''),
  moduleName: z.string().min(1, 'Module name is required'),
  moduleCode: z.string().min(1, 'Module code is required'),
  displayName: z.string().default(''),
  moduleCategory: z.string().default('QMS'),
  description: z.string().default(''),
  displayOrder: z.coerce.number().min(0).default(0),
  sortOrder: z.coerce.number().min(0).default(0),
  menuGroup: z.string().default(''),
  navigationPath: z.string().default(''),
  route: z.string().default(''),
  icon: z.string().default(''),
  version: z.string().default('1.0.0'),
  buildNumber: z.string().default(''),
  isEnabled: z.boolean().default(true),
  isInstalled: z.boolean().default(true),
  isSystemModule: z.boolean().default(false),
  isCritical: z.boolean().default(false),
  isVisible: z.boolean().default(true),
  visibility: z.enum(MODULE_VISIBILITY_STATUSES).default('Visible'),
  licenseStatus: z.enum(MODULE_LICENSE_STATUSES).default('Licensed'),
  featureStatus: z.enum(MODULE_FEATURE_STATUSES).default('GA'),
  environment: z.enum(SYSTEM_ENVIRONMENTS).default('Production'),
  company: z.string().default(''),
  businessUnit: z.string().default(''),
  site: z.string().default(''),
  department: z.string().default(''),
  requiredRole: z.string().default(''),
  dependencies: z.array(z.string()).default([]),
  featureFlags: z.array(z.object({
    key: z.string(),
    label: z.string().default(''),
    enabled: z.boolean().default(false),
    rollout: z.enum(['Off', 'Beta', 'Experimental', 'GA']).default('Off'),
    roles: z.array(z.string()).default([]),
    departments: z.array(z.string()).default([]),
    sites: z.array(z.string()).default([]),
  })).default([]),
  configurationJson: z.string().default('{}'),
  isDeleted: z.boolean().optional(),
  remarks: z.string().default(''),
  changeReason: z.string().optional(),
});

export const moduleConfigFormSchema = z.object({
  moduleCode: z.string().min(1, 'Module code is required').max(40),
  moduleName: z.string().min(1, 'Module name is required').max(120),
  displayName: z.string().default(''),
  moduleCategory: z.string().min(1, 'Category is required'),
  description: z.string().default(''),
  displayOrder: z.coerce.number().min(0).default(0),
  menuGroup: z.string().default(''),
  navigationPath: z.string().default(''),
  icon: z.string().default(''),
  version: z.string().default('1.0.0'),
  buildNumber: z.string().default(''),
  isEnabled: z.boolean().default(true),
  isInstalled: z.boolean().default(true),
  isSystemModule: z.boolean().default(false),
  isCritical: z.boolean().default(false),
  isVisible: z.boolean().default(true),
  visibility: z.enum(MODULE_VISIBILITY_STATUSES).default('Visible'),
  licenseStatus: z.enum(MODULE_LICENSE_STATUSES).default('Licensed'),
  featureStatus: z.enum(MODULE_FEATURE_STATUSES).default('GA'),
  environment: z.enum(SYSTEM_ENVIRONMENTS).default('Production'),
  company: z.string().default(''),
  businessUnit: z.string().default(''),
  site: z.string().default(''),
  department: z.string().default(''),
  requiredRole: z.string().default(''),
  dependencies: z.string().default(''),
  featureFlagsJson: z.string().default('[]'),
  configurationJson: z.string().default('{}'),
  remarks: z.string().default(''),
  changeReason: z.string().min(5, 'Change reason is required (min 5 characters)'),
}).refine(
  (data) => {
    try {
      JSON.parse(data.configurationJson || '{}');
      return true;
    } catch {
      return false;
    }
  },
  { message: 'Configuration JSON must be valid JSON', path: ['configurationJson'] },
).refine(
  (data) => {
    try {
      const parsed = JSON.parse(data.featureFlagsJson || '[]');
      return Array.isArray(parsed);
    } catch {
      return false;
    }
  },
  { message: 'Feature flags must be a valid JSON array', path: ['featureFlagsJson'] },
);

export const emailSmsTemplateSchema = z.object({
  ...baseFields,
  templateId: z.string().default(''),
  templateCode: z.string().min(1, 'Template code is required'),
  templateName: z.string().min(1, 'Template name is required'),
  description: z.string().default(''),
  category: z.string().default('General'),
  module: z.string().default(''),
  subModule: z.string().default(''),
  workflow: z.string().default(''),
  templateType: z.enum(TEMPLATE_TYPES).default('Email'),
  channel: z.string().default('Email'),
  subject: z.string().default(''),
  body: z.string().min(1, 'Body is required'),
  smsBody: z.string().default(''),
  htmlBody: z.string().default(''),
  isHtml: z.boolean().default(false),
  variables: z.string().default(''),
  placeholders: z.array(z.string()).default([]),
  priority: z.enum(NOTIFICATION_PRIORITIES).default('Medium'),
  language: z.string().default('en'),
  company: z.string().default(''),
  businessUnit: z.string().default(''),
  site: z.string().default(''),
  department: z.string().default(''),
  version: z.coerce.number().min(1).default(1),
  effectiveDate: z.string().default(''),
  reviewDate: z.string().default(''),
  expiryDate: z.string().default(''),
  approvalStatus: z.enum(TEMPLATE_APPROVAL_STATUSES).default('Draft'),
  isDeleted: z.boolean().optional(),
  remarks: z.string().default(''),
  changeReason: z.string().optional(),
});

export const emailSmsTemplateFormSchema = z.object({
  templateCode: z.string().min(1, 'Template code is required').max(80),
  templateName: z.string().min(1, 'Template name is required').max(200),
  description: z.string().default(''),
  category: z.string().min(1, 'Category is required'),
  module: z.string().min(1, 'Module is required'),
  subModule: z.string().default(''),
  workflow: z.string().default(''),
  templateType: z.enum(TEMPLATE_TYPES).default('Email'),
  subject: z.string().default(''),
  body: z.string().min(1, 'Message body is required'),
  smsBody: z.string().default(''),
  isHtml: z.boolean().default(false),
  variables: z.string().default(''),
  priority: z.enum(NOTIFICATION_PRIORITIES).default('Medium'),
  language: z.string().default('en'),
  company: z.string().default(''),
  businessUnit: z.string().default(''),
  site: z.string().default(''),
  department: z.string().default(''),
  effectiveDate: z.string().default(''),
  reviewDate: z.string().default(''),
  expiryDate: z.string().default(''),
  approvalStatus: z.enum(TEMPLATE_APPROVAL_STATUSES).default('Draft'),
  remarks: z.string().default(''),
  changeReason: z.string().min(5, 'Change reason is required (min 5 characters)'),
}).refine(
  (data) => data.templateType !== 'Email' || data.subject.trim().length > 0,
  { message: 'Subject is required for Email templates', path: ['subject'] },
).refine(
  (data) => data.templateType !== 'SMS' || (data.smsBody || data.body).trim().length > 0,
  { message: 'SMS body is required', path: ['smsBody'] },
).refine(
  (data) => data.templateType !== 'SMS' || (data.smsBody || data.body).length <= 1600,
  { message: 'SMS body exceeds 1600 characters (multipart limit)', path: ['smsBody'] },
);

export const masterDataImportExportSchema = z.object({
  ...baseFields,
  operationId: z.string().min(1, 'Operation ID is required'),
  operationType: z.enum(['Import', 'Export', 'Validate', 'Rollback']).default('Export'),
  masterType: z.string().min(1, 'Master type is required'),
  masterCollection: z.string().default(''),
  fileName: z.string().default(''),
  fileFormat: z.string().default('JSON'),
  importMode: z.string().default('Dry Run'),
  recordCount: z.coerce.number().min(0).default(0),
  successCount: z.coerce.number().min(0).default(0),
  errorCount: z.coerce.number().min(0).default(0),
  skippedCount: z.coerce.number().min(0).default(0),
  operationDate: z.string().default(''),
  performedBy: z.string().default(''),
  performedByUid: z.string().default(''),
  operationStatus: z.enum(MASTER_DATA_OPERATION_STATUSES).default('Queued'),
  errorLog: z.string().default(''),
  validationSummary: z.string().default(''),
  mappingProfile: z.string().default(''),
  changeReason: z.string().default(''),
  isDeleted: z.boolean().optional(),
  checksum: z.string().default(''),
  durationMs: z.coerce.number().min(0).default(0),
});

export const masterDataImportExportFormSchema = z.object({
  masterType: z.string().min(1, 'Master type is required'),
  importMode: z.enum(MASTER_DATA_IMPORT_MODES).default('Dry Run'),
  fileFormat: z.enum(MASTER_DATA_EXPORT_FORMATS).default('JSON'),
  changeReason: z.string().min(5, 'Change reason is required (min 5 characters)'),
});

/** Legacy schema for backup_restore collection compatibility */
export const backupRestoreSchema = backupHistorySchema.extend({
  restorePoint: z.string().default(''),
  restoreHistory: z.string().default(''),
});

export type AdminUser = z.infer<typeof adminUserSchema>;
export type AdminRole = z.infer<typeof roleSchema>;
export type PermissionMatrix = z.infer<typeof permissionMatrixSchema>;
export type RoleFormData = z.infer<typeof roleFormSchema>;
export type RoleMatrixModule = typeof ROLE_MATRIX_MODULES[number];
export type RoleMatrixAction = typeof ROLE_MATRIX_ACTIONS[number];
export type Department = z.infer<typeof departmentSchema>;
export type DepartmentFormData = z.infer<typeof departmentFormSchema>;
export type Designation = z.infer<typeof designationSchema>;
export type DesignationFormData = z.infer<typeof designationFormSchema>;
export type CompanySite = z.infer<typeof companySiteSchema>;
export type CompanySiteFormData = z.infer<typeof companySiteFormSchema>;
export type AdminProduct = z.infer<typeof adminProductSchema>;
export type ProductFormData = z.infer<typeof productFormSchema>;
export type ProductCompositionRow = z.infer<typeof productCompositionRowSchema>;
export type ProductPackingRow = z.infer<typeof productPackingRowSchema>;
export type ProductAttachment = z.infer<typeof productAttachmentSchema>;
export type AdminBatch = z.infer<typeof adminBatchSchema>;
export type BatchFormData = z.infer<typeof batchFormSchema>;
export type BatchAttachment = z.infer<typeof batchAttachmentSchema>;
export type Parameter = z.infer<typeof parameterSchema>;
export type ParameterFormData = z.infer<typeof parameterFormSchema>;
export type Workflow = z.infer<typeof workflowSchema>;
export type WorkflowStep = z.infer<typeof workflowStepSchema>;
export type WorkflowFormData = z.infer<typeof workflowFormSchema>;
export type ApprovalMatrix = z.infer<typeof approvalMatrixSchema>;
export type ApprovalMatrixFormData = z.infer<typeof approvalMatrixFormSchema>;
export type DocumentNumbering = z.infer<typeof documentNumberingSchema>;
export type DocumentNumberingFormData = z.infer<typeof documentNumberingFormSchema>;
export type AdminAuditLog = z.infer<typeof auditLogSchema>;
export type AuditTrailEntry = z.infer<typeof auditTrailEntrySchema>;
export type EsignSettings = z.infer<typeof esignSettingsSchema>;
export type EsignSettingFormData = z.infer<typeof esignSettingFormSchema>;
export type EsignRecord = z.infer<typeof esignRecordSchema>;
export type NotificationSetting = z.infer<typeof notificationSettingSchema>;
export type NotificationSettingFormData = z.infer<typeof notificationSettingFormSchema>;
export type BackupHistory = z.infer<typeof backupHistorySchema>;
export type BackupFormData = z.infer<typeof backupFormSchema>;
export type BackupSettings = z.infer<typeof backupSettingsSchema>;
export type RestoreHistory = z.infer<typeof restoreHistorySchema>;
export type RestoreRequestFormData = z.infer<typeof restoreRequestFormSchema>;
export type SystemSettings = z.infer<typeof systemSettingsSchema>;
export type LoginActivity = z.infer<typeof loginActivitySchema>;
export type AccessReview = z.infer<typeof accessReviewSchema>;
export type PasswordPolicy = z.infer<typeof passwordPolicySchema>;
export type ModuleConfig = z.infer<typeof moduleConfigSchema>;
export type ModuleConfigFormData = z.infer<typeof moduleConfigFormSchema>;
export type EmailSmsTemplate = z.infer<typeof emailSmsTemplateSchema>;
export type EmailSmsTemplateFormData = z.infer<typeof emailSmsTemplateFormSchema>;
export type MasterDataImportExport = z.infer<typeof masterDataImportExportSchema>;
export type MasterDataImportExportFormData = z.infer<typeof masterDataImportExportFormSchema>;
export type BackupRestore = z.infer<typeof backupRestoreSchema>;
